//! Foreign procedure invocation support for generated SDK bindings.

use std::{
    collections::{HashMap, HashSet},
    env, fs,
    path::{Path, PathBuf},
};

use heck::{ToKebabCase, ToSnakeCase, ToUpperCamelCase};
use miden_assembly_syntax::ast::{Path as MasmPath, PathComponent};
use miden_mast_package::{Package, PackageExport};
use miden_protocol::utils::serde::Deserializable;
use proc_macro2::{Span, TokenStream as TokenStream2};
use quote::quote;
use syn::{
    Attribute, Error, File, ImplItem, ImplItemFn, Item, ItemFn, ItemImpl, ItemStruct, ReturnType,
    parse_quote,
};
use wit_bindgen_core::wit_parser::{
    Docs, Function, FunctionKind, InterfaceId, Param, Resolve, Span as WitSpan, Type as WitType,
    WorldId, WorldItem,
};

use crate::{
    generate::{
        collect_arg_idents, format_module_path, qualify_signature_types, should_generate_struct,
    },
    wit_world::{ManifestPackage, MidenDependency},
};

/// WIT function prefix used for foreign procedure imports.
pub(crate) const WIT_FUNCTION_PREFIX: &str = "fpi-";

/// Rust identifier prefix generated by wit-bindgen for FPI WIT functions.
pub(crate) const RUST_FUNCTION_PREFIX: &str = "fpi_";

/// Adds `fpi-` functions to imported Miden dependency interfaces in the selected world.
pub(crate) fn inject_imports(
    resolve: &mut Resolve,
    world_id: WorldId,
    dependency_imports: &[String],
) -> syn::Result<()> {
    if dependency_imports.is_empty() {
        return Ok(());
    }

    let dependency_imports = dependency_imports.iter().map(String::as_str).collect::<HashSet<_>>();
    let imported_interfaces = resolve.worlds[world_id]
        .imports
        .values()
        .filter_map(|item| match item {
            WorldItem::Interface { id, .. } => Some(*id),
            _ => None,
        })
        .filter(|id| {
            interface_import_path(resolve, *id)
                .as_ref()
                .is_some_and(|path| dependency_imports.contains(path.as_str()))
        })
        .collect::<Vec<_>>();

    if imported_interfaces.is_empty() {
        return Ok(());
    }

    let core_types = resolve_core_types(resolve)?;
    for interface_id in imported_interfaces {
        inject_functions_into_interface(resolve, interface_id, core_types);
    }

    Ok(())
}

/// Adds typed FPI wrapper structs to generated Rust bindings.
pub(crate) fn augment_bindings(file: &mut File) -> syn::Result<()> {
    let mut modules = Vec::new();
    collect_modules(&file.items, &mut Vec::new(), &mut modules)?;
    check_struct_name_collisions(&modules)?;

    if modules.is_empty() {
        return Ok(());
    }

    let dependencies = load_dependencies(Span::call_site())?;
    let mut include_paths = Vec::new();
    for module in modules {
        let Some(dependency) = dependencies
            .iter()
            .find(|dependency| dependency.module_path == module.path_string)
        else {
            return Err(Error::new(
                Span::call_site(),
                format!(
                    "failed to resolve FPI dependency metadata for generated module `{}`",
                    module.path_string
                ),
            ));
        };

        include_paths.push(dependency.package_path.clone());
        let (struct_item, impl_item) = build_struct(&module, dependency)?;
        file.items.push(Item::Struct(struct_item));
        file.items.push(Item::Impl(impl_item));
    }

    for path in include_paths {
        let utf8_path = path.to_str().ok_or_else(|| {
            Error::new(
                Span::call_site(),
                format!("path '{}' contains invalid UTF-8", path.display()),
            )
        })?;
        file.items.push(parse_quote! {
            const _: &[u8] = include_bytes!(#utf8_path);
        });
    }

    Ok(())
}

/// Determines whether a generated free function represents an FPI WIT import.
pub(crate) fn is_function(func: &ItemFn) -> bool {
    matches!(func.vis, syn::Visibility::Public(_))
        && func.sig.unsafety.is_none()
        && func.sig.ident.to_string().starts_with(RUST_FUNCTION_PREFIX)
}

/// Core WIT types needed to synthesize caller-only FPI imports.
#[derive(Clone, Copy)]
struct CoreTypes {
    felt: WitType,
    word: WitType,
}

/// FPI-capable generated import module.
struct Module {
    /// Rust module path where the generated `fpi_*` free functions live.
    module_path: Vec<syn::Ident>,
    /// String form of `module_path` used for dependency lookup.
    path_string: String,
    /// Generated FPI free functions from this import module.
    functions: Vec<ItemFn>,
}

/// Resolved package data needed to generate FPI caller wrappers.
struct Dependency {
    /// Rust module path generated by wit-bindgen for the dependency import.
    module_path: String,
    /// Miden package artifact read for procedure roots.
    package_path: PathBuf,
    /// Fully-qualified WIT import path.
    import: String,
    /// Procedure roots keyed by full WIT interface path and function name.
    roots: HashMap<ProcedureRootKey, ProcedureRoot>,
}

/// Identifies a WIT procedure export in a dependency package.
#[derive(Clone, Debug, Eq, Hash, PartialEq)]
struct ProcedureRootKey {
    /// Fully-qualified WIT interface path, including package version.
    interface: String,
    /// WIT function name.
    function: String,
}

/// Four field elements that make up a foreign procedure root.
#[derive(Clone, Copy)]
struct ProcedureRoot {
    felts: [u64; 4],
}

impl ProcedureRootKey {
    /// Creates a root key for one WIT interface function.
    fn new(interface: impl Into<String>, function: impl Into<String>) -> Self {
        Self {
            interface: interface.into(),
            function: function.into(),
        }
    }
}

/// Returns the fully-qualified import path used for a resolved interface.
fn interface_import_path(resolve: &Resolve, interface_id: InterfaceId) -> Option<String> {
    let interface = &resolve.interfaces[interface_id];
    let interface_name = interface.name.as_deref()?;
    let package_id = interface.package?;
    Some(resolve.packages[package_id].name.interface_id(interface_name))
}

/// Resolves `felt` and `word` from `miden:base/core-types`.
fn resolve_core_types(resolve: &Resolve) -> syn::Result<CoreTypes> {
    let core_types = resolve
        .packages
        .iter()
        .find_map(|(_, package)| {
            if package.name.namespace != "miden" || package.name.name != "base" {
                return None;
            }

            package.interfaces.get("core-types").map(|interface_id| {
                let interface = &resolve.interfaces[*interface_id];
                (interface.types.get("felt").copied(), interface.types.get("word").copied())
            })
        })
        .ok_or_else(|| {
            Error::new(
                Span::call_site(),
                "failed to resolve miden:base/core-types package for FPI imports",
            )
        })?;

    let (Some(felt), Some(word)) = core_types else {
        return Err(Error::new(
            Span::call_site(),
            "miden:base/core-types is missing felt or word type definitions",
        ));
    };

    Ok(CoreTypes {
        felt: WitType::Id(felt),
        word: WitType::Id(word),
    })
}

/// Injects FPI variants of every freestanding function in an imported interface.
fn inject_functions_into_interface(
    resolve: &mut Resolve,
    interface_id: InterfaceId,
    core_types: CoreTypes,
) {
    let interface = &mut resolve.interfaces[interface_id];
    let functions = interface
        .functions
        .values()
        .filter(|function| {
            matches!(function.kind, FunctionKind::Freestanding)
                && !function.name.starts_with(WIT_FUNCTION_PREFIX)
        })
        .cloned()
        .collect::<Vec<_>>();

    for function in functions {
        let fpi_name = format!("{WIT_FUNCTION_PREFIX}{}", function.name);
        if interface.functions.contains_key(&fpi_name) {
            continue;
        }

        interface
            .functions
            .insert(fpi_name.clone(), build_import_function(function, fpi_name, core_types));
    }
}

/// Builds the caller-side WIT import that forwards through `execute_foreign_procedure`.
fn build_import_function(function: Function, fpi_name: String, core_types: CoreTypes) -> Function {
    let mut params = Vec::with_capacity(function.params.len() + 3);
    params.push(Param {
        name: "account-id-prefix".to_string(),
        ty: core_types.felt,
        span: WitSpan::default(),
    });
    params.push(Param {
        name: "account-id-suffix".to_string(),
        ty: core_types.felt,
        span: WitSpan::default(),
    });
    params.push(Param {
        name: "foreign-proc-root".to_string(),
        ty: core_types.word,
        span: WitSpan::default(),
    });
    params.extend(function.params);

    Function {
        name: fpi_name,
        kind: FunctionKind::Freestanding,
        params,
        result: function.result,
        docs: Docs::default(),
        stability: function.stability,
        span: WitSpan::default(),
    }
}

/// Recursively walks all modules and collects FPI functions from leaf import modules.
fn collect_modules(
    items: &[Item],
    path: &mut Vec<syn::Ident>,
    modules_out: &mut Vec<Module>,
) -> syn::Result<()> {
    for item in items.iter() {
        if let Item::Mod(module) = item {
            path.push(module.ident.clone());
            if let Some((_, ref content)) = module.content {
                collect_modules(content, path, modules_out)?;
                collect_functions_from_module(content, path, modules_out);
            }
            path.pop();
        }
    }

    Ok(())
}

/// Collects generated `fpi_*` free functions from a leaf import module.
fn collect_functions_from_module(
    items: &[Item],
    path: &[syn::Ident],
    modules_out: &mut Vec<Module>,
) {
    if !should_generate_struct(path, items) {
        return;
    }

    let functions = items
        .iter()
        .filter_map(|item| match item {
            Item::Fn(func) if is_function(func) => Some(func.clone()),
            _ => None,
        })
        .collect::<Vec<_>>();

    if functions.is_empty() {
        return;
    }

    modules_out.push(Module {
        module_path: path.to_vec(),
        path_string: format_module_path(path),
        functions,
    });
}

/// Builds a `CounterContract`-style FPI caller wrapper for a generated import module.
fn build_struct(module: &Module, dependency: &Dependency) -> syn::Result<(ItemStruct, ItemImpl)> {
    let struct_ident = struct_ident(module)?;
    let struct_doc = format!("FPI caller for procedures imported from `{}`.", dependency.import);
    let struct_item: ItemStruct = parse_quote! {
        #[doc = #struct_doc]
        #[derive(Clone, Copy, Debug)]
        pub struct #struct_ident(::miden::AccountId);
    };

    let mut impl_item: ItemImpl = parse_quote! {
        impl #struct_ident {
            /// Creates a caller bound to the given foreign account.
            #[inline(always)]
            pub fn from_account(account_id: ::miden::AccountId) -> Self {
                Self(account_id)
            }
        }
    };

    for func in &module.functions {
        let wit_name = function_wit_name(func)?;
        let root_key = ProcedureRootKey::new(dependency.import.as_str(), wit_name.as_str());
        let root = dependency.roots.get(&root_key).ok_or_else(|| {
            Error::new(
                func.sig.ident.span(),
                format!(
                    "failed to find procedure root for `{}#{wit_name}` in package '{}'",
                    dependency.import,
                    dependency.package_path.display()
                ),
            )
        })?;
        impl_item
            .items
            .push(ImplItem::Fn(build_wrapper_method(func, &module.module_path, *root)?));
    }

    Ok((struct_item, impl_item))
}

/// Builds a method on an FPI caller wrapper that delegates to the generated `fpi_*` import.
fn build_wrapper_method(
    func: &ItemFn,
    module_path: &[syn::Ident],
    procedure_root: ProcedureRoot,
) -> syn::Result<ImplItemFn> {
    let original_fn_ident = func.sig.ident.clone();
    let method_ident = method_ident(func)?;
    let mut sig = func.sig.clone();
    sig.ident = method_ident;

    let retained_inputs = sig.inputs.iter().skip(3).cloned().collect::<Vec<_>>();
    if sig.inputs.len() < 3 {
        return Err(Error::new(
            sig.ident.span(),
            "generated FPI function is missing account id and procedure root parameters",
        ));
    }

    sig.inputs.clear();
    sig.inputs.push(parse_quote!(&self));
    sig.inputs.extend(retained_inputs);
    qualify_signature_types(&mut sig, module_path);

    let arg_idents = collect_arg_idents(func)?.into_iter().skip(3).collect::<Vec<_>>();
    let root_tokens = procedure_root_tokens(procedure_root);
    let call_expr = wrapper_call_tokens(module_path, &original_fn_ident, root_tokens, &arg_idents);

    let method_doc = format!(
        "Invokes `{}` through `execute_foreign_procedure`.",
        sig.ident.to_string().to_kebab_case()
    );
    let doc_attr: Attribute = parse_quote!(#[doc = #method_doc]);
    let inline_attr: Attribute = parse_quote!(#[inline(always)]);

    let body_tokens = match &sig.output {
        ReturnType::Default => quote!({ #call_expr; }),
        _ => quote!({ #call_expr }),
    };
    let block = syn::parse2(body_tokens)?;

    Ok(ImplItemFn {
        attrs: vec![doc_attr, inline_attr],
        vis: func.vis.clone(),
        defaultness: None,
        sig,
        block,
    })
}

/// Generates tokens for calling a generated FPI free function from its typed wrapper.
fn wrapper_call_tokens(
    module_path: &[syn::Ident],
    fn_ident: &syn::Ident,
    procedure_root: TokenStream2,
    args: &[syn::Ident],
) -> TokenStream2 {
    let mut path_tokens = quote! { crate::bindings };
    for ident in module_path {
        path_tokens = quote! { #path_tokens :: #ident };
    }

    quote! {
        #path_tokens :: #fn_ident(self.0.prefix, self.0.suffix, #procedure_root, #(#args),*)
    }
}

/// Returns the user-facing struct identifier for a generated FPI import module.
fn struct_ident(module: &Module) -> syn::Result<syn::Ident> {
    let Some(last) = module.module_path.last() else {
        return Err(Error::new(Span::call_site(), "empty FPI module path"));
    };
    Ok(syn::Ident::new(&last.to_string().to_upper_camel_case(), last.span()))
}

/// Returns the wrapper method name for a generated FPI free function.
fn method_ident(func: &ItemFn) -> syn::Result<syn::Ident> {
    let fn_name = func.sig.ident.to_string();
    let Some(method_name) = fn_name.strip_prefix(RUST_FUNCTION_PREFIX) else {
        return Err(Error::new(
            func.sig.ident.span(),
            format!(
                "expected generated FPI function name to start with `{}`",
                RUST_FUNCTION_PREFIX
            ),
        ));
    };
    Ok(syn::Ident::new(method_name, func.sig.ident.span()))
}

/// Returns the original WIT function name represented by a generated FPI free function.
fn function_wit_name(func: &ItemFn) -> syn::Result<String> {
    Ok(method_ident(func)?.to_string().to_kebab_case())
}

/// Converts a procedure root into SDK `Word` construction tokens.
fn procedure_root_tokens(root: ProcedureRoot) -> TokenStream2 {
    let felts = root.felts.into_iter().map(|value| quote!(::miden::felt!(#value)));
    quote!(::miden::Word::new([#(#felts),*]))
}

/// Loads all Miden dependency packages needed by generated FPI wrappers.
fn load_dependencies(error_span: Span) -> syn::Result<Vec<Dependency>> {
    let manifest = ManifestPackage::load(error_span)?;
    manifest
        .collect_miden_dependencies(error_span)?
        .into_iter()
        .map(load_dependency)
        .collect()
}

/// Loads a single dependency package and extracts exported procedure roots.
fn load_dependency(dependency: MidenDependency) -> syn::Result<Dependency> {
    let module_path = import_module_path(&dependency.import);
    let package_path = resolve_dependency_package_path(&dependency)?;
    let package_bytes = fs::read(&package_path).map_err(|err| {
        Error::new(
            Span::call_site(),
            format!("failed to read dependency package '{}': {err}", package_path.display()),
        )
    })?;
    let package = Package::read_from_bytes(&package_bytes).map_err(|err| {
        Error::new(
            Span::call_site(),
            format!("failed to deserialize dependency package '{}': {err}", package_path.display()),
        )
    })?;

    let mut roots = HashMap::new();
    for export in package.manifest.exports() {
        let PackageExport::Procedure(proc_export) = export else {
            continue;
        };
        let Some(root_key) = procedure_root_key_from_export_path(proc_export.path.as_ref()) else {
            continue;
        };
        if root_key.interface != dependency.import {
            continue;
        }
        roots.insert(root_key, procedure_root_from_digest(&proc_export.digest));
    }

    Ok(Dependency {
        module_path,
        package_path,
        import: dependency.import,
        roots,
    })
}

/// Converts a fully-qualified WIT import path into the Rust module path generated by wit-bindgen.
fn import_module_path(import: &str) -> String {
    let without_version = import.split('@').next().unwrap_or(import);
    without_version
        .split([':', '/'])
        .filter(|segment| !segment.is_empty())
        .map(|segment| segment.to_snake_case())
        .collect::<Vec<_>>()
        .join("::")
}

/// Finds the `.masp` package artifact corresponding to a manifest dependency entry.
fn resolve_dependency_package_path(dependency: &MidenDependency) -> syn::Result<PathBuf> {
    if dependency.root.is_file() {
        return Ok(dependency.root.clone());
    }

    let preferred_profile = env::var("PROFILE").unwrap_or_else(|_| "debug".to_string());
    let mut profiles = vec![preferred_profile.clone()];
    if preferred_profile != "release" {
        profiles.push("release".to_string());
    }
    if preferred_profile != "debug" {
        profiles.push("debug".to_string());
    }

    let package_stems = dependency_package_stems(dependency);
    let output_dirs = dependency_output_dirs(dependency, &profiles);
    for dir in &output_dirs {
        if let Some(package) = find_dependency_package_in_dir(dir, &package_stems)? {
            return Ok(package.clone());
        }
    }

    let searched = output_dirs
        .iter()
        .map(|dir| format!("'{}'", dir.display()))
        .collect::<Vec<_>>()
        .join(", ");
    Err(Error::new(
        Span::call_site(),
        format!(
            "failed to find built `.masp` artifact for dependency '{}'; searched {searched}; \
             build the dependency with `cargo miden build` first",
            dependency.name,
        ),
    ))
}

/// Returns candidate output directories where a dependency `.masp` may have been written.
fn dependency_output_dirs(dependency: &MidenDependency, profiles: &[String]) -> Vec<PathBuf> {
    let mut dirs = Vec::new();

    if let Ok(target_dir) = env::var("CARGO_TARGET_DIR") {
        push_profile_dirs(&mut dirs, PathBuf::from(target_dir), profiles);
    }

    if let Ok(out_dir) = env::var("OUT_DIR") {
        for ancestor in Path::new(&out_dir).ancestors() {
            push_profile_dirs(&mut dirs, ancestor.to_path_buf(), profiles);
        }
    }

    // When Cargo builds a dependency with `CARGO_TARGET_DIR` set, `cargo miden build` writes the
    // fresh `.masp` there. Keep the dependency-local target as a fallback so stale restored
    // artifacts cannot shadow the package that was just built for this compilation.
    push_profile_dirs(&mut dirs, dependency.root.join("target"), profiles);

    dirs
}

/// Adds `target/miden/<profile>` directories while preserving insertion order.
fn push_profile_dirs(dirs: &mut Vec<PathBuf>, target_root: PathBuf, profiles: &[String]) {
    for profile in profiles {
        let dir = target_root.join("miden").join(profile);
        if !dirs.iter().any(|existing| existing == &dir) {
            dirs.push(dir);
        }
    }
}

/// Finds a dependency package in `dir`, preferring filenames that match the package name.
fn find_dependency_package_in_dir(
    dir: &Path,
    package_stems: &[String],
) -> syn::Result<Option<PathBuf>> {
    if !dir.is_dir() {
        return Ok(None);
    }

    let mut packages = fs::read_dir(dir)
        .map_err(|err| {
            Error::new(
                Span::call_site(),
                format!("failed to read dependency output directory '{}': {err}", dir.display()),
            )
        })?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|err| {
            Error::new(
                Span::call_site(),
                format!("failed to iterate dependency output directory '{}': {err}", dir.display()),
            )
        })?
        .into_iter()
        .map(|entry| entry.path())
        .filter(|path| path.extension().is_some_and(|ext| ext == "masp"))
        .collect::<Vec<_>>();
    packages.sort();

    for stem in package_stems {
        if let Some(package) = packages.iter().find(|path| {
            path.file_stem()
                .and_then(|value| value.to_str())
                .is_some_and(|file_stem| file_stem == stem)
        }) {
            return Ok(Some(package.clone()));
        }
    }

    Ok((packages.len() == 1).then(|| packages[0].clone()))
}

/// Returns likely `.masp` filename stems for a dependency.
fn dependency_package_stems(dependency: &MidenDependency) -> Vec<String> {
    let mut stems = Vec::new();

    if let Some(package_name) = dependency_manifest_package_name(&dependency.root) {
        push_dependency_stem(&mut stems, &package_name);
    }

    if let Some(name) = dependency.name.split([':', '/']).next_back() {
        push_dependency_stem(&mut stems, name);
    }

    if let Some(name) = dependency.root.file_name().and_then(|name| name.to_str()) {
        push_dependency_stem(&mut stems, name);
    }

    stems
}

/// Reads the Cargo package name for dependency directories.
fn dependency_manifest_package_name(root: &Path) -> Option<String> {
    let manifest_path = root.join("Cargo.toml");
    let manifest = fs::read_to_string(manifest_path).ok()?;
    let manifest = manifest.parse::<toml::Table>().ok()?;
    manifest
        .get("package")
        .and_then(toml::Value::as_table)
        .and_then(|package| package.get("name"))
        .and_then(toml::Value::as_str)
        .map(ToOwned::to_owned)
}

/// Adds a normalized Miden package stem if it has not already been added.
fn push_dependency_stem(stems: &mut Vec<String>, name: &str) {
    let stem = name.replace('-', "_");
    if !stem.is_empty() && !stems.iter().any(|existing| existing == &stem) {
        stems.push(stem);
    }
}

/// Extracts the WIT interface/function key encoded in a package procedure export path.
fn procedure_root_key_from_export_path(path: &MasmPath) -> Option<ProcedureRootKey> {
    let interface = single_non_root_path_component(path.parent()?)?;
    let function = path.last()?;
    Some(ProcedureRootKey::new(interface, function))
}

/// Returns the only non-root path component if `path` has exactly one.
fn single_non_root_path_component(path: &MasmPath) -> Option<&str> {
    let mut component = None;

    for next in path.components() {
        let next = next.ok()?;
        match next {
            PathComponent::Root => continue,
            PathComponent::Normal(_) => {
                if component.replace(next.as_str()).is_some() {
                    return None;
                }
            }
        }
    }

    component
}

/// Converts a MAST digest word into literal field elements.
fn procedure_root_from_digest(digest: &miden_protocol::Word) -> ProcedureRoot {
    let elements = digest.as_elements();
    ProcedureRoot {
        felts: [
            elements[0].as_canonical_u64(),
            elements[1].as_canonical_u64(),
            elements[2].as_canonical_u64(),
            elements[3].as_canonical_u64(),
        ],
    }
}

/// Checks for wrapper struct name collisions across FPI import modules.
fn check_struct_name_collisions(modules: &[Module]) -> syn::Result<()> {
    let mut seen: HashMap<String, &str> = HashMap::new();

    for module in modules {
        let struct_name = struct_ident(module)?.to_string();
        if let Some(existing_path) = seen.get(&struct_name) {
            return Err(Error::new(
                Span::call_site(),
                format!(
                    "FPI wrapper struct name collision: `{struct_name}` is generated for both \
                     `{existing_path}` and `{}`",
                    module.path_string
                ),
            ));
        }

        seen.insert(struct_name, &module.path_string);
    }

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn procedure_root_key_uses_full_wit_interface_component() {
        let path =
            MasmPath::validate(r#"::"miden:no-arg-account/no-arg-account@0.0.1"::"get-count""#)
                .expect("fixture path must be valid");

        let key = procedure_root_key_from_export_path(path)
            .expect("WIT export path must produce a procedure root key");

        assert_eq!(
            key,
            ProcedureRootKey::new("miden:no-arg-account/no-arg-account@0.0.1", "get-count")
        );
    }

    #[test]
    fn procedure_root_key_rejects_nested_non_wit_export_path() {
        let path = MasmPath::validate(
            r#"::"miden:no-arg-note/no-arg-note@0.0.1"::no_arg_note::cabi_realloc"#,
        )
        .expect("fixture path must be valid");

        assert_eq!(procedure_root_key_from_export_path(path), None);
    }

    #[test]
    fn procedure_root_key_separates_same_function_in_different_interfaces() {
        let first = ProcedureRootKey::new("miden:foo/account@0.0.1", "get-count");
        let second = ProcedureRootKey::new("miden:foo/account-admin@0.0.1", "get-count");

        assert_ne!(first, second);
    }
}
