//! Shared definitions for foreign procedure invocation macro support.

/// WIT function prefix used for foreign procedure imports.
pub(crate) const WIT_FUNCTION_PREFIX: &str = "fpi-";

/// Rust identifier prefix generated by wit-bindgen for FPI WIT functions.
pub(crate) const RUST_FUNCTION_PREFIX: &str = "fpi_";
