//! Utilities for resolving WIT paths from Cargo.toml manifest metadata.

use std::{
    env, fs,
    io::ErrorKind,
    path::{Path, PathBuf},
};

use proc_macro2::Span;
use syn::Error;

use crate::{
    dependency_package::{DependencyWitSource, collect_dependency_wit_sources},
    util::{bundled_wit_folder, strip_line_comment},
    wit_world::ProjectPackageMetadata,
};

/// File name for the embedded Miden SDK WIT.
const SDK_WIT_FILE_NAME: &str = "miden.wit";

/// Embedded Miden SDK WIT source.
pub(crate) const SDK_WIT_SOURCE: &str = include_str!("../wit/miden.wit");

/// WIT metadata extracted from the consuming crate.
pub(crate) struct ResolvedWit {
    /// WIT search paths loaded before any dependency source (the SDK prelude).
    pub paths: Vec<String>,
    /// WIT sources read from the compiled packages of Miden path dependencies.
    pub dependency_sources: Vec<DependencyWitSource>,
    /// The crate's local `wit/` directory, loaded after the dependency sources so its WIT can
    /// import the dependency packages.
    pub local_wit_root: Option<PathBuf>,
    /// The `package/world` id detected in the local WIT directory, used for wit-bindgen world
    /// selection.
    pub world: Option<String>,
    /// The world-defining local WIT file, present when it is the crate's only WIT file and can
    /// therefore be embedded verbatim as the component's public WIT.
    pub embeddable_local_wit: Option<PathBuf>,
}

#[derive(Default)]
pub(crate) struct ResolveOptions {
    pub allow_missing_local_wit: bool,
}

/// Collects WIT search paths and the target world from `miden-project.toml` + local files.
pub(crate) fn resolve_wit_paths(options: ResolveOptions) -> Result<ResolvedWit, Error> {
    let manifest = ProjectPackageMetadata::load_or_default(Span::call_site())?;

    let canonical_prelude_dir = ensure_sdk_wit()?;

    let mut resolved = Vec::new();

    let prelude_dir = canonical_prelude_dir
        .to_str()
        .ok_or_else(|| {
            Error::new(
                Span::call_site(),
                format!("path '{}' contains invalid UTF-8", canonical_prelude_dir.display()),
            )
        })?
        .to_owned();

    resolved.push(prelude_dir);

    // Dependency WIT is read from each path dependency's compiled `.masp` package rather than
    // from files on disk; the sources are pushed into the wit-bindgen resolver alongside the
    // file-based paths collected here.
    let dependency_sources =
        collect_dependency_wit_sources(&manifest.manifest_dir, &manifest.package)?;

    let raw_local_wit_root = Path::new(&manifest.manifest_dir).join("wit");
    let mut local_wit_root = None;
    let mut world = None;
    let mut embeddable_local_wit = None;

    if raw_local_wit_root.exists() && !options.allow_missing_local_wit {
        let local_root = fs::canonicalize(&raw_local_wit_root).unwrap_or(raw_local_wit_root);
        if let Some(local_world) = detect_world(&local_root)? {
            world = Some(local_world.world);
            embeddable_local_wit = local_world.embeddable_file;
        }
        local_wit_root = Some(local_root);
    }

    Ok(ResolvedWit {
        paths: resolved,
        dependency_sources,
        local_wit_root,
        world,
        embeddable_local_wit,
    })
}

/// Ensures the embedded Miden SDK WIT is materialized in the project's folder.
fn ensure_sdk_wit() -> Result<PathBuf, Error> {
    let autogenerated_wit_folder = bundled_wit_folder()?;

    let sdk_wit_path = autogenerated_wit_folder.join(SDK_WIT_FILE_NAME);
    let sdk_version: &str = env!("CARGO_PKG_VERSION");
    let expected_source = format!(
        "/// NOTE: This file is auto-generated from the Miden SDK.\n/// Version: \
         v{sdk_version}\n/// Any manual edits will be overwritten.\n\n{SDK_WIT_SOURCE}"
    );
    let should_write_wit = match fs::read_to_string(&sdk_wit_path) {
        Ok(existing) => existing != expected_source,
        Err(err) if err.kind() == ErrorKind::NotFound => true,
        Err(err) => {
            return Err(Error::new(
                Span::call_site(),
                format!("failed to read '{}': {err}", sdk_wit_path.display()),
            ));
        }
    };

    if should_write_wit {
        fs::write(&sdk_wit_path, expected_source).map_err(|err| {
            Error::new(
                Span::call_site(),
                format!("failed to write '{}': {err}", sdk_wit_path.display()),
            )
        })?;
    }

    Ok(fs::canonicalize(&autogenerated_wit_folder).unwrap_or(autogenerated_wit_folder))
}

/// A world detected in the crate's local `wit` directory.
struct LocalWorld {
    /// `package/world` id used for wit-bindgen world selection.
    world: String,
    /// The world-defining WIT file, present when it is the directory's only WIT file and can
    /// therefore be embedded verbatim as the component's public WIT.
    embeddable_file: Option<PathBuf>,
}

/// Scans the component's `wit` directory to find the default world.
fn detect_world(wit_root: &Path) -> Result<Option<LocalWorld>, Error> {
    let mut entries = fs::read_dir(wit_root)
        .map_err(|err| {
            Error::new(Span::call_site(), format!("failed to read '{}': {err}", wit_root.display()))
        })?
        .collect::<Result<Vec<_>, _>>()
        .map_err(|err| {
            Error::new(
                Span::call_site(),
                format!("failed to iterate '{}': {err}", wit_root.display()),
            )
        })?;
    entries.sort_by_key(|entry| entry.file_name());

    let wit_files = entries
        .into_iter()
        .map(|entry| entry.path())
        .filter(|path| {
            !path.file_name().is_some_and(|name| name == "deps")
                && !path.is_dir()
                && path.extension().and_then(|ext| ext.to_str()) == Some("wit")
        })
        .collect::<Vec<_>>();

    for path in &wit_files {
        if let Some((package, world)) = parse_package_and_world(path)? {
            let embeddable_file = (wit_files.len() == 1).then(|| path.clone());
            return Ok(Some(LocalWorld {
                world: format!("{package}/{world}"),
                embeddable_file,
            }));
        }
    }

    Ok(None)
}

/// Parses a WIT source file for its package declaration and first world definition.
fn parse_package_and_world(path: &Path) -> Result<Option<(String, String)>, Error> {
    let contents = fs::read_to_string(path).map_err(|err| {
        Error::new(
            Span::call_site(),
            format!("failed to read WIT file '{}': {err}", path.display()),
        )
    })?;

    let package = extract_package_name(&contents);
    let world = extract_world_name(&contents);

    match (package, world) {
        (Some(package), Some(world)) => Ok(Some((package, world))),
        _ => Ok(None),
    }
}

/// Returns the package identifier from a WIT source string, if present.
fn extract_package_name(contents: &str) -> Option<String> {
    for line in contents.lines() {
        let trimmed = strip_line_comment(line).trim_start();
        if let Some(rest) = trimmed.strip_prefix("package ") {
            let mut token = rest.trim();
            if let Some(idx) = token.find(';') {
                token = &token[..idx];
            }
            let mut name = token.trim();
            if let Some(idx) = name.find('@') {
                name = &name[..idx];
            }
            return Some(name.trim().to_string());
        }
    }
    None
}

/// Extracts the first world identifier from a WIT source string.
pub(crate) fn extract_world_name(contents: &str) -> Option<String> {
    for line in contents.lines() {
        let trimmed = strip_line_comment(line).trim_start();
        if let Some(rest) = trimmed.strip_prefix("world ") {
            let mut name = String::new();
            for ch in rest.trim().chars() {
                if ch.is_alphanumeric() || ch == '-' || ch == '_' {
                    name.push(ch);
                } else {
                    break;
                }
            }
            if !name.is_empty() {
                return Some(name);
            }
        }
    }
    None
}
