//! Naming rules shared by the macros that derive WIT functions from Rust items.
//!
//! A Rust identifier maps to a canonical WIT name, which is written in explicit (`%`) form in the
//! generated WIT, and which wit-bindgen maps back to the Rust identifier of the generated guest
//! trait method.

use heck::ToKebabCase;
use proc_macro2::Span;
use syn::ext::IdentExt;

/// Converts a Rust identifier to its canonical WIT spelling before WIT escaping is applied.
///
/// Returns an error at the identifier's span when the derived name is not a valid WIT name.
pub(crate) fn rust_ident_to_wit_name(ident: &syn::Ident) -> syn::Result<String> {
    let wit_name = ident.unraw().to_string().to_kebab_case();
    if wit_bindgen_core::wit_parser::validate_id(&wit_name).is_err() {
        return Err(syn::Error::new(
            ident.span(),
            format!(
                "`{ident}` has no valid WIT name (derived `{wit_name}`): WIT names are ASCII \
                 words `[a-z][a-z0-9]*` joined by `-`, the first starting with a letter; rename it"
            ),
        ));
    }
    Ok(wit_name)
}

/// Returns the Rust trait-method identifier generated by wit-bindgen for a canonical WIT name.
///
/// `wit_name` must come from [`rust_ident_to_wit_name`].
pub(crate) fn wit_bindgen_guest_ident(wit_name: &str, span: Span) -> syn::Ident {
    let guest_name = wit_bindgen_rust::to_rust_ident(wit_name);
    debug_assert!(
        syn::parse_str::<syn::Ident>(&guest_name).is_ok(),
        "`{wit_name}` was validated as a WIT name, so its guest identifier `{guest_name}` is valid"
    );
    syn::Ident::new(&guest_name, span)
}

/// Renders WIT's explicit identifier form.
///
/// Explicit identifiers are valid for both keywords and ordinary identifiers. Using this form for
/// every Rust-derived function, parameter, field and case name keeps them valid without checking
/// them against WIT's keyword list; type, package and interface names are rendered bare and
/// still are.
pub(crate) fn explicit_wit_identifier(name: &str) -> String {
    format!("%{name}")
}
