//! Helpers for rendering inline WIT documents shared across SDK proc macros.

use std::fmt::Write;

use semver::Version;

/// Builds inline WIT documents shared by the SDK macros.
pub(crate) struct WitBuilder {
    source: String,
}

impl WitBuilder {
    /// Initializes a WIT document with the generator banner and package declaration.
    pub(crate) fn new(generated_by: &str, package_name: &str, package_version: &Version) -> Self {
        let package_with_version = package_with_version(package_name, package_version);
        let mut source = String::new();
        let _ = writeln!(source, "// This file is auto-generated by the `{generated_by}` macro.");
        let _ = writeln!(source, "// Do not edit this file manually.");
        source.push('\n');
        let _ = writeln!(source, "package {package_with_version};");
        source.push('\n');

        Self { source }
    }

    /// Writes a top-level `use` directive.
    pub(crate) fn use_path(&mut self, path: &str) {
        let _ = writeln!(self.source, "use {path};");
    }

    /// Inserts a blank line at the current top-level position.
    pub(crate) fn blank_line(&mut self) {
        self.source.push('\n');
    }

    /// Writes an `interface` block and returns the closure result.
    pub(crate) fn interface<T>(
        &mut self,
        name: &str,
        build: impl FnOnce(&mut WitBody<'_>) -> T,
    ) -> T {
        let _ = writeln!(self.source, "interface {name} {{");
        let result = build(&mut WitBody::new(&mut self.source, 1));
        let _ = writeln!(self.source, "}}");
        result
    }

    /// Writes a `world` block and returns the closure result.
    pub(crate) fn world<T>(&mut self, name: &str, build: impl FnOnce(&mut WitBody<'_>) -> T) -> T {
        let _ = writeln!(self.source, "world {name} {{");
        let result = build(&mut WitBody::new(&mut self.source, 1));
        let _ = writeln!(self.source, "}}");
        result
    }

    /// Finishes rendering and returns the final WIT source.
    pub(crate) fn finish(self) -> String {
        self.source
    }
}

/// Writes indented lines inside a WIT interface or world block.
pub(crate) struct WitBody<'a> {
    source: &'a mut String,
    indent_level: usize,
}

impl<'a> WitBody<'a> {
    /// Creates a new indented writer for a WIT block body.
    fn new(source: &'a mut String, indent_level: usize) -> Self {
        Self {
            source,
            indent_level,
        }
    }

    /// Writes a single line at the current indentation level.
    pub(crate) fn line(&mut self, line: &str) {
        self.write_indent();
        let _ = writeln!(self.source, "{line}");
    }

    /// Inserts a blank line inside the current WIT block.
    pub(crate) fn blank_line(&mut self) {
        self.source.push('\n');
    }

    /// Writes a nested block with one extra indentation level for its body.
    pub(crate) fn block(&mut self, header: &str, build: impl FnOnce(&mut WitBody<'_>)) {
        self.line(header);
        build(&mut WitBody::new(self.source, self.indent_level + 1));
        self.line("}");
    }

    /// Writes the current indentation prefix.
    fn write_indent(&mut self) {
        for _ in 0..self.indent_level {
            self.source.push_str("    ");
        }
    }
}

/// Formats a WIT package identifier with an explicit version suffix.
fn package_with_version(package_name: &str, package_version: &Version) -> String {
    if package_name.contains('@') {
        package_name.to_string()
    } else {
        format!("{package_name}@{package_version}")
    }
}

#[cfg(test)]
mod tests {
    use semver::Version;

    use super::WitBuilder;

    #[test]
    fn renders_nested_blocks_with_expected_indentation() {
        let mut wit = WitBuilder::new("#[test]", "miden:test", &Version::new(1, 0, 0));
        wit.use_path("miden:base/core-types@1.0.0");
        wit.blank_line();
        wit.interface("foo", |interface| {
            interface.line("use core-types.{word};");
            interface.blank_line();
            interface.block("record payload {", |record| {
                record.line("value: word,");
            });
        });
        wit.blank_line();
        wit.world("foo-world", |world| {
            world.line("export foo;");
        });

        let expected = r#"// This file is auto-generated by the `#[test]` macro.
// Do not edit this file manually.

package miden:test@1.0.0;

use miden:base/core-types@1.0.0;

interface foo {
    use core-types.{word};

    record payload {
        value: word,
    }
}

world foo-world {
    export foo;
}
"#;

        assert_eq!(wit.finish(), expected);
    }
}
