//! Bindings generated from the Miden package manifests, one module per package.
//!
//! Regenerated by `tests/generated.rs` (`UPDATE_BINDINGS=1`); never edited by hand.

/// The protocol library (`miden-protocol`), mounted at its root `::miden::protocol`.
// Generated names follow MASM's spelling, wrappers take one parameter per operand, and the
// generated items carry the MASM path as their doc rather than prose.
#[allow(non_camel_case_types, non_snake_case, clippy::too_many_arguments, missing_docs)]
#[rustfmt::skip]
pub mod protocol;

/// The standards library (`miden-standards`), mounted at its root `::miden::standards`. Its
/// signatures use the protocol's types, which they name through [`protocol`].
// The same allowances as `protocol`, for the same reasons.
#[allow(non_camel_case_types, non_snake_case, clippy::too_many_arguments, missing_docs)]
#[rustfmt::skip]
pub mod standards;
