package miden:storage-example@1.0.0;

use miden:base/core-types@1.0.0;

interface foo {
    use core-types.{felt, word};

    test-storage-item: func(index: felt, value: word) -> felt;
    test-storage-map-item: func(index: felt, key: word, value: word) -> felt;
}

world foo-world {
    include miden:core-import/all@1.0.0;

    export foo;
}
