package miden:storage-example@1.0.0;

use miden:base/core-types@1.0.0;

interface foo {
    use core-types.{asset-amount, word, asset};

    set-asset-qty: func(pub-key: word, asset: asset, qty: asset-amount);
    get-asset-qty: func(asset: asset) -> asset-amount;
}

world foo-world {
    export foo;
}
