use miden_stdlib_sys::Word;

use super::types::{AccountId, AssetId, Nonce, StorageSlotId};
use crate::raw::protocol::active_account as raw;

/// Returns the account ID of the active account.
pub fn get_id() -> AccountId {
    raw::get_id().into()
}

/// Returns the nonce of the active account.
#[inline]
pub fn get_nonce() -> Nonce {
    Nonce {
        inner: raw::get_nonce(),
    }
}

/// Returns the code commitment of the active account.
#[inline]
pub fn get_code_commitment() -> Word {
    raw::get_code_commitment()
}

/// Computes the latest storage commitment of the active account.
#[inline]
pub fn compute_storage_commitment() -> Word {
    raw::compute_storage_commitment()
}

/// Returns the current value stored under the specified `asset_id` in the active account vault.
pub fn get_asset(asset_id: AssetId) -> Word {
    raw::get_asset(asset_id.inner)
}

/// Returns `true` if the active account vault currently contains an asset with the specified asset
/// id.
#[inline]
pub fn has_asset(asset_id: AssetId) -> bool {
    raw::has_asset(asset_id.inner)
}

/// Returns the current vault root of the active account.
#[inline]
pub fn get_vault_root() -> Word {
    raw::get_vault_root()
}

/// Returns the number of procedures exported by the active account.
#[inline]
pub fn get_num_procedures() -> u32 {
    raw::get_num_procedures().into()
}

/// Returns the procedure root for the procedure at `index`.
///
/// # Panics
///
/// Panics if `index` exceeds `u8::MAX`, the largest procedure index the protocol accepts.
#[inline]
pub fn get_procedure_root(index: u32) -> Word {
    raw::get_procedure_root(u8::try_from(index).expect("procedure index exceeds u8"))
}

/// Returns `true` if the procedure identified by `proc_root` exists on the active account.
#[inline]
pub fn has_procedure(proc_root: Word) -> bool {
    raw::has_procedure(proc_root)
}

/// Trait that provides active account operations for components.
///
/// This trait is automatically implemented for the storage struct marked with the
/// `#[component_storage]` macro.
///
/// A `#[account(...)]` component method that shares a name with one of these built-ins does not
/// shadow it: both live on traits, so the call is disambiguated with
/// `<Wallet as ActiveAccount>::get_id(account)` or `<Wallet as Interface>::get_id(account)`.
pub trait ActiveAccount {
    /// Guard hook invoked by every active-account operation before it runs.
    ///
    /// The default implementation is a no-op. Types that can also represent a *foreign* account
    /// (for example the struct generated by the `#[account(...)]` macro) override this to reject
    /// calls made on a foreign binding, because the active-account operations always target the
    /// transaction's active account rather than the foreign one.
    #[doc(hidden)]
    #[inline]
    fn __assert_active_account(&self) {}

    /// Returns the account ID of the active account.
    #[inline]
    fn get_id(&self) -> AccountId {
        self.__assert_active_account();
        get_id()
    }

    /// Returns the nonce of the active account.
    #[inline]
    fn get_nonce(&self) -> Nonce {
        self.__assert_active_account();
        get_nonce()
    }

    /// Returns the code commitment of the active account.
    #[inline]
    fn get_code_commitment(&self) -> Word {
        self.__assert_active_account();
        get_code_commitment()
    }

    /// Computes the latest storage commitment of the active account.
    #[inline]
    fn compute_storage_commitment(&self) -> Word {
        self.__assert_active_account();
        compute_storage_commitment()
    }

    /// Returns the current value stored under the specified `asset_id` in the active account
    /// vault.
    #[inline]
    fn get_asset(&self, asset_id: AssetId) -> Word {
        self.__assert_active_account();
        get_asset(asset_id)
    }

    /// Returns `true` if the active account vault currently contains an asset with the specified
    /// asset id.
    #[inline]
    fn has_asset(&self, asset_id: AssetId) -> bool {
        self.__assert_active_account();
        has_asset(asset_id)
    }

    /// Returns the current vault root of the active account.
    #[inline]
    fn get_vault_root(&self) -> Word {
        self.__assert_active_account();
        get_vault_root()
    }

    /// Returns the number of procedures exported by the active account.
    #[inline]
    fn get_num_procedures(&self) -> u32 {
        self.__assert_active_account();
        get_num_procedures()
    }

    /// Returns the procedure root for the procedure at `index`.
    #[inline]
    fn get_procedure_root(&self, index: u32) -> Word {
        self.__assert_active_account();
        get_procedure_root(index)
    }

    /// Returns `true` if the procedure identified by `proc_root` exists on the active account.
    #[inline]
    fn has_procedure(&self, proc_root: Word) -> bool {
        self.__assert_active_account();
        has_procedure(proc_root)
    }

    /// Returns `true` if the active account has a storage slot with the given slot id.
    #[inline]
    fn has_storage_slot(&self, slot_id: StorageSlotId) -> bool {
        self.__assert_active_account();
        super::storage::has_storage_slot(slot_id)
    }
}

/// Marker trait for account API wrapper types.
///
/// The `#[note]` and `#[tx_script]` macros instantiate their entrypoint account parameter
/// through this trait, so that parameter must be a type implementing it. The `ActiveAccount`
/// supertrait guarantees that parameter is usable as the transaction's active account and keeps
/// unrelated `Default` types from satisfying the bound. The `#[account(...)]` macro implements
/// both automatically; it is not a sealed capability boundary, so manual implementations are
/// possible but normally unnecessary.
#[diagnostic::on_unimplemented(
    message = "`{Self}` is not an account wrapper generated by `#[account(...)]`",
    note = "define a struct with `#[account(...)]` and use it as the entrypoint account parameter"
)]
pub trait AccountWrapper: ActiveAccount + Default {
    /// Creates a binding to the transaction's active account.
    ///
    /// This is the account the transaction executes against, as opposed to a foreign account
    /// reached through FPI (created with `new`).
    #[inline(always)]
    fn active() -> Self {
        Self::default()
    }
}

/// Exposes which account a generated `#[account(...)]` wrapper binds to.
///
/// The component traits generated by `#[account(...)]` dispatch every call between the
/// transaction's active account and a foreign account reached through FPI. They read the binding
/// target through this trait — a supertrait of each generated component trait — so the dispatch
/// works without access to the wrapper's private `foreign_account_id` field.
///
/// This is an internal dispatch hook implemented by the `#[account(...)]` macro; it is not meant to
/// be implemented or called directly.
#[doc(hidden)]
pub trait AccountBinding {
    /// Returns `Some(id)` when the wrapper targets a foreign account reached through FPI, or `None`
    /// when it targets the transaction's active account.
    fn foreign_account_id(&self) -> Option<AccountId>;
}
