use super::*;

/// Ensures a single embedded component WIT source is recognized as one package.
#[test]
fn component_wit_counts_a_single_package_declaration() {
    let wit = r#"// This file is auto-generated by the `#[component]` macro.
package miden:basic-wallet@0.1.0;

use miden:base/core-types@1.0.0;

interface basic-wallet {
    receive-asset: func();
}

world basic-wallet-world {
    export basic-wallet;
}
"#;

    assert_eq!(count_top_level_wit_packages(wit), 1);
}

/// Ensures concatenated WIT sections (two linked `#[component]` implementations) are detected.
#[test]
fn component_wit_detects_concatenated_package_declarations() {
    let wit = r#"package miden:first@0.1.0;

world first-world {
}
package miden:second@0.1.0;

world second-world {
}
"#;

    assert_eq!(count_top_level_wit_packages(wit), 2);
}

/// Ensures nested package declarations and comments are not counted as top-level packages.
#[test]
fn component_wit_ignores_nested_packages_and_comments() {
    let wit = r#"// package miden:commented@0.1.0;
package miden:outer@0.1.0;

package miden:nested@0.1.0 {
    interface api {
        get: func() -> u64;
    }
}
"#;

    assert_eq!(count_top_level_wit_packages(wit), 1);
}

/// Ensures a one-line package declaration followed by other items on the same line is counted.
///
/// WIT is whitespace-insensitive; the `{` of a following item must not disqualify the
/// declaration, while a nested `package <id> { ... }` (whose `{` precedes any `;`) still must.
#[test]
fn component_wit_counts_one_line_package_declarations() {
    let wit =
        "package miden:x@1.0.0; interface api { get: func() -> u64; }\n\nworld w { export api; }\n";
    assert_eq!(count_top_level_wit_packages(wit), 1);

    let nested_one_liner = "package miden:nested@0.1.0 { interface api { get: func() -> u64; } }\n";
    assert_eq!(count_top_level_wit_packages(nested_one_liner), 0);

    let concatenated = "package miden:first@0.1.0; world first-world { }\npackage \
                        miden:second@0.1.0; world second-world { }\n";
    assert_eq!(count_top_level_wit_packages(concatenated), 2);
}

/// Ensures declarations inside (nested) block comments are not counted as top-level packages.
#[test]
fn component_wit_ignores_block_commented_packages() {
    let wit = r#"/* legacy:
package miden:old@0.1.0;
/* nested comment with package miden:inner@0.1.0; */
still commented
*/
package miden:new@0.1.0;
"#;

    assert_eq!(count_top_level_wit_packages(wit), 1);
}

/// Documents the detector's boundary: byte-wise gluing without a newline hides the second
/// declaration. The producers therefore wrap every embedded WIT payload in boundary newlines
/// (`normalize_embedded_wit` in the SDK macros), which keeps concatenated sections detectable.
#[test]
fn component_wit_concatenation_needs_boundary_newlines() {
    let first_without_trailing_newline = "package miden:first@0.1.0;\n\nworld first-world {\n}";
    let second = "package miden:second@0.1.0;\n\nworld second-world {\n}\n";

    let glued = format!("{first_without_trailing_newline}{second}");
    assert_eq!(count_top_level_wit_packages(&glued), 1);

    let normalized = format!("\n{first_without_trailing_newline}\n\n{second}\n");
    assert_eq!(count_top_level_wit_packages(&normalized), 2);
}

/// Ensures duplicate `#[auth_script]` metadata across modules is rejected at merge time.
#[test]
fn component_frontend_metadata_rejects_duplicate_auth_exports() {
    let modules = [
        ParsedModule {
            component_frontend_metadata: Some(FrontendMetadata::AuthScript {
                method_path: "crate::auth::AuthA::authenticate".to_string(),
                export_name: "auth_a".to_string(),
            }),
            ..Default::default()
        },
        ParsedModule {
            component_frontend_metadata: Some(FrontendMetadata::AuthScript {
                method_path: "crate::auth::AuthB::authenticate".to_string(),
                export_name: "auth_b".to_string(),
            }),
            ..Default::default()
        },
    ];

    let err = merge_frontend_metadata(modules.iter()).unwrap_err();

    assert!(
        err.to_string().contains("multiple `#[auth_script]` procedures were found"),
        "unexpected error: {err:?}"
    );
    assert!(
        err.to_string().contains("crate::auth::AuthA::authenticate"),
        "unexpected error: {err:?}"
    );
}

/// Ensures duplicate `#[note_script]` metadata across modules is rejected at merge time.
#[test]
fn component_frontend_metadata_rejects_duplicate_note_script_exports() {
    let modules = [
        ParsedModule {
            component_frontend_metadata: Some(FrontendMetadata::NoteScript {
                method_path: "crate::notes::NoteA::execute".to_string(),
                export_name: "note_a".to_string(),
            }),
            ..Default::default()
        },
        ParsedModule {
            component_frontend_metadata: Some(FrontendMetadata::NoteScript {
                method_path: "crate::notes::NoteB::execute".to_string(),
                export_name: "note_b".to_string(),
            }),
            ..Default::default()
        },
    ];

    let err = merge_frontend_metadata(modules.iter()).unwrap_err();

    assert!(
        err.to_string().contains("multiple `#[note_script]` procedures were found"),
        "unexpected error: {err:?}"
    );
    assert!(
        err.to_string().contains("crate::notes::NoteA::execute"),
        "unexpected error: {err:?}"
    );
}

/// Ensures mixed frontend metadata kinds across modules are rejected at merge time.
#[test]
fn component_frontend_metadata_rejects_mixed_export_kinds() {
    let modules = [
        ParsedModule {
            component_frontend_metadata: Some(FrontendMetadata::AuthScript {
                method_path: "crate::auth::AuthComponent::authenticate".to_string(),
                export_name: "auth".to_string(),
            }),
            ..Default::default()
        },
        ParsedModule {
            component_frontend_metadata: Some(FrontendMetadata::NoteScript {
                method_path: "crate::notes::PaymentNote::execute".to_string(),
                export_name: "note".to_string(),
            }),
            ..Default::default()
        },
    ];

    let err = merge_frontend_metadata(modules.iter()).unwrap_err();

    assert!(
        err.to_string()
            .contains("both `#[auth_script]` and `#[note_script]` procedures were found"),
        "unexpected error: {err:?}"
    );
    assert!(
        err.to_string().contains("crate::auth::AuthComponent::authenticate"),
        "unexpected error: {err:?}"
    );
}

/// Ensures metadata validation reports when a marked export was not lifted into the component.
#[test]
fn component_frontend_metadata_reports_missing_lifted_exports() {
    let metadata = FrontendMetadata::AuthScript {
        method_path: "crate::auth::AuthComponent::authenticate".to_string(),
        export_name: "auth".to_string(),
    };
    let lifted_exports = FxHashSet::default();

    let err =
        validate_lifted_frontend_metadata_exports(Some(&metadata), &lifted_exports).unwrap_err();

    assert!(
        err.to_string().contains(
            "failed to find the component export marked with `#[auth_script]`: \
             `crate::auth::AuthComponent::authenticate`"
        ),
        "unexpected error: {err:?}"
    );
    assert!(
        err.to_string().contains("expected lifted export `auth`"),
        "unexpected error: {err:?}"
    );
}
