// Generated by miden-sdk-bindgen: linker stubs for package `fixture` 0.0.0.
// Dependency commitment: 0x8d2ff29823f2db597e12e84e8ea429ec23e5181631bc7be0df6576729d916ff9.
// Do not edit: regenerate from the package.
//
// Every stub is a weak definition of the symbol a binding declares, with a diverging body:
// the Wasm frontend recognizes the name and lowers the call to the Miden procedure. Weak
// linkage lets more than one crate carry stubs for the same package.
#![no_std]
#![feature(linkage, optimize_attribute)]
// A stub is named after its procedure's path with `::` written `__`: not snake case.
#![allow(non_snake_case)]

#[unsafe(export_name = "fixture::boxed")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__boxed(
    _arg0: i32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::bytes")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__bytes(_arg0: i32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::cursor")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__cursor() -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::delta")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__delta(_arg0: i32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::hash")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__hash(_arg0: f32, _arg1: f32, _arg2: f32, _arg3: f32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::id")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__id(_arg0: f32) -> f32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::is_set")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__is_set(_arg0: i32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::kind_of")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__kind_of(_arg0: i32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::make_pair")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__make_pair(_arg0: f32, _arg1: f32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::many")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__many(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::nested::outer")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__nested__outer(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::nested::unwrap")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__nested__unwrap(
    _arg0: f32,
    _arg1: f32,
    _arg2: i32,
    _arg3: i32,
    _arg4: i32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::nested::wrap")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__nested__wrap(_arg0: f32, _arg1: f32, _arg2: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::owner")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__owner(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::set_owner")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__set_owner(_arg0: f32, _arg1: f32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::spaced")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__spaced(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::stamp")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__stamp(_arg0: i32, _arg1: i64, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::swap")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__swap(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::tag_of")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__tag_of(_arg0: f32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::take_pair")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__take_pair(_arg0: f32, _arg1: f32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::wide")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__wide(_arg0: i64) -> i64 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::word_stamp")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__word_stamp(_arg0: f32, _arg1: f32, _arg2: f32, _arg3: f32, _arg4: i64) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "fixture::write")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn fixture__write(_arg0: i32, _arg1: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}
