//! The Rust backend's module tree, type definitions and constants.
//!
//! The bindings mirror the package's MASM modules below [`Options::root`]: the root's items sit at
//! the top level of the text, and every module below it is a `pub mod`. Each module holds, in this
//! order: the import of the support items, the type definitions (by path, each preceded by the
//! types the bindings declare for it, then the types only signatures use), the constants (by
//! path), the bindable procedures (by path, written by [`procedures`]), and the child modules (by
//! name).

use std::collections::BTreeMap;

use miden_assembly_syntax::{
    ast::{
        ConstantValue, HashKind, Path, PathBuf,
        types::{EnumType, StructType, Type, TypeRepr},
    },
    parser::IntValue,
};
use miden_core::{events::EventId, utils::hash_string_to_word};
use midenc_package_interface::{
    ConstantItem, LoweredSignature, PackageInterface, ProcedureItem, TypeItem,
};

use crate::{
    Error, Options, Skipped, layout, names, procedures,
    render::{ARRAY_WIDTH, MAX_WIDTH, RESULT, Writer},
    types::{self, LocalType, SUPPORT_ITEMS, TypeUniverse},
};

/// What every generated struct and enum derives. Every type a field can have implements these.
const DERIVES: &str = "#[derive(Clone, Copy, Debug, PartialEq, Eq)]";

/// Why a string constant produces no code.
const STRING_CONSTANT: &str = "string constants have no Rust form";

/// The bindings text of `package`: the header, then the module tree with its types and constants.
///
/// A string constant produces no code; it is added to `skipped`.
pub(crate) fn bindings(
    package: &PackageInterface,
    universe: &TypeUniverse<'_>,
    options: &Options,
    skipped: &mut Vec<Skipped>,
) -> Result<String, Error> {
    let tree = Module::tree(package, &options.root)?;
    let mut w = Writer::new();
    header(&mut w, package, options);
    w.blank();
    tree.emit(&mut w, package, universe, options, skipped)?;
    Ok(w.finish())
}

/// The comment the text starts with: where it comes from, and how it is meant to be mounted.
fn header(w: &mut Writer, package: &PackageInterface, options: &Options) {
    let name: &str = package.name.as_ref();
    w.line(&format!(
        "// Generated by miden-sdk-bindgen from package `{name}` {}.",
        package.version
    ));
    w.line(&format!("// Dependency commitment: {}.", package.digest.to_hex()));
    w.line("// Do not edit: regenerate from the package.");
    w.line("//");
    w.line(&format!(
        "// Root `{}` is mounted here; support items come from `{}`.",
        options.root, options.support
    ));
    w.line("// This file carries no inner attributes: the module that includes it allows");
    w.line("// `non_camel_case_types`, `non_snake_case`, `clippy::too_many_arguments` and");
    w.line("// `missing_docs`.");
    w.line("//");
    w.line(
        "// A struct MASM code writes through a pointer is read by Rust as it is: a `bool` field",
    );
    w.line(
        "// holding anything but 0 or 1, or an enum field holding an undeclared discriminant, is",
    );
    w.line(
        "// undefined behaviour. The same holds of a procedure's declared result type: the binding",
    );
    w.line(
        "// trusts the manifest, and a procedure that leaves a value outside its declared type is",
    );
    w.line("// the package's bug, not something the wrapper masks.");
}

/// One generated module: the MASM module it mirrors, and the exports that go in it.
struct Module<'a> {
    /// The MASM path of the module.
    path: PathBuf,
    /// Its type exports, by path.
    types: Vec<&'a TypeItem>,
    /// Its constants, by path.
    constants: Vec<&'a ConstantItem>,
    /// Its bindable procedures, by path, each with its Wasm shape.
    procedures: Vec<(&'a ProcedureItem, &'a LoweredSignature)>,
    /// The modules below it, by MASM name.
    children: BTreeMap<String, Module<'a>>,
}

impl<'a> Module<'a> {
    fn new(path: PathBuf) -> Self {
        Self {
            path,
            types: Vec::new(),
            constants: Vec::new(),
            procedures: Vec::new(),
            children: BTreeMap::new(),
        }
    }

    /// The module tree of `package` below `root`, every type, constant and bindable procedure in
    /// its module.
    ///
    /// Every module and export must lie under `root`, else [`Error::OutsideRoot`]; the modules
    /// above it (`::miden` above `::miden::core`) are only the way down to it, and are left out.
    fn tree(package: &'a PackageInterface, root: &str) -> Result<Self, Error> {
        let mut top = Module::new(Path::new(root).to_path_buf());
        // Sorted, so a module comes after its ancestors and takes its own manifest path.
        for module in package.module_paths() {
            if names::is_above_root(root, &module)? {
                continue;
            }
            let segments = names::under_root(root, &module)?;
            top.descendant(&segments).path = module.clone();
        }
        for item in &package.types {
            top.module_of(root, &item.path)?.types.push(item);
        }
        for item in &package.constants {
            top.module_of(root, &item.path)?.constants.push(item);
        }
        for (item, lowered) in package.bindable() {
            top.module_of(root, &item.path)?.procedures.push((item, lowered));
        }
        Ok(top)
    }

    /// The module at `segments` below this one, created as needed.
    fn descendant(&mut self, segments: &[&str]) -> &mut Self {
        let mut module = self;
        for segment in segments {
            let path = module.path.join(*segment);
            module =
                module.children.entry(segment.to_string()).or_insert_with(|| Module::new(path));
        }
        module
    }

    /// The module the export at `path` goes in.
    fn module_of(&mut self, root: &str, path: &Path) -> Result<&mut Self, Error> {
        let segments = names::under_root(root, path)?;
        let Some((_, modules)) = segments.split_last() else {
            // The root is a module, not an export under it.
            return Err(Error::OutsideRoot {
                path: path.to_string(),
                root: root.to_string(),
            });
        };
        Ok(self.descendant(modules))
    }

    /// Write this module's items, then its children, at the writer's current level.
    ///
    /// A type export with no Rust form, a string constant, and a procedure whose types have no
    /// Rust form or whose name another procedure or constant of the module has, produce no code
    /// and are added to `skipped`.
    fn emit(
        &self,
        w: &mut Writer,
        package: &PackageInterface,
        universe: &TypeUniverse<'_>,
        options: &Options,
        skipped: &mut Vec<Skipped>,
    ) -> Result<(), Error> {
        let at: &Path = &self.path;
        let mut exports = Vec::with_capacity(self.types.len());
        for item in &self.types {
            match layout::check(&item.ty) {
                Ok(()) => exports.push(*item),
                Err(reason) => skipped.push(Skipped {
                    path: item.path.to_string(),
                    reason,
                }),
            }
        }
        let mut constants = Vec::with_capacity(self.constants.len());
        for item in &self.constants {
            match constant(&item.value) {
                Some(value) => constants.push((*item, value)),
                None => skipped.push(Skipped {
                    path: item.path.to_string(),
                    reason: STRING_CONSTANT.to_string(),
                }),
            }
        }
        self.check_type_names(&exports)?;
        self.check_module_names(universe, &exports)?;
        let mut collisions = self.check_value_names(&constants)?;
        let mut items = Separator::default();

        let imported: Vec<&str> =
            SUPPORT_ITEMS.into_iter().filter(|name| !universe.defines(at, name)).collect();
        if !imported.is_empty() {
            items.next(w);
            w.line("#[allow(unused_imports)]");
            use_line(w, &options.support, &imported);
        }

        let locals: Vec<&LocalType> = universe
            .local_types()
            .iter()
            .filter(|local| types::same_module(&local.module, at))
            .collect();
        for item in exports {
            for local in locals.iter().filter(|local| local.before.as_ref() == Some(&item.path)) {
                items.next(w);
                emit_local(w, universe, local)?;
            }
            items.next(w);
            emit_type(w, universe, item, at)?;
        }
        for local in locals.iter().filter(|local| local.before.is_none()) {
            items.next(w);
            emit_local(w, universe, local)?;
        }

        for (item, (constant, source)) in constants {
            items.next(w);
            emit_constant(w, universe, item, at, constant, source);
        }

        for (item, lowered) in &self.procedures {
            if let Some(reason) = collisions.remove(&item.path.to_string()) {
                skipped.push(Skipped {
                    path: item.path.to_string(),
                    reason,
                });
                continue;
            }
            // A procedure whose types have no Rust form is reported rather than written.
            let mut wrapper = w.nested();
            match procedures::emit(&mut wrapper, item, lowered, package, universe) {
                Ok(()) => {
                    items.next(w);
                    w.append(wrapper);
                }
                Err(Error::Unsupported { reason, .. }) => skipped.push(Skipped {
                    path: item.path.to_string(),
                    reason,
                }),
                Err(err) => return Err(err),
            }
        }

        for (name, child) in &self.children {
            items.next(w);
            w.open(&format!("pub mod {}", names::module_ident(name)));
            child.emit(w, package, universe, options, skipped)?;
            w.close();
        }
        Ok(())
    }

    /// Two of this module's type exports `exports` that have the same Rust name are
    /// [`Error::ConflictingType`]. (The types the bindings declare are checked as they are
    /// declared.)
    fn check_type_names(&self, exports: &[&TypeItem]) -> Result<(), Error> {
        let idents = exports.iter().map(|item| ((), types::export_name(item)));
        match names::duplicate(idents) {
            Some(((), (), name)) => Err(Error::ConflictingType {
                module: self.path.to_string(),
                name,
            }),
            None => Ok(()),
        }
    }

    /// A child module whose Rust name another child, or a type this module defines (one of its
    /// type `exports` or a type the bindings declare here), has is [`Error::ConflictingName`]:
    /// modules and types share Rust's type namespace.
    fn check_module_names(
        &self,
        universe: &TypeUniverse<'_>,
        exports: &[&TypeItem],
    ) -> Result<(), Error> {
        let at: &Path = &self.path;
        let exports = exports.iter().map(|item| (item.path.to_string(), types::export_name(item)));
        let locals = universe
            .local_types()
            .iter()
            .filter(|local| types::same_module(&local.module, at))
            .map(|local| (format!("{at}::{}", local.name), local.name.clone()));
        let children = self
            .children
            .iter()
            .map(|(name, child)| (child.path.to_string(), names::module_ident(name)));
        match names::duplicate(exports.chain(locals).chain(children)) {
            Some((first, second, name)) => Err(Error::ConflictingName {
                first,
                second,
                name,
            }),
            None => Ok(()),
        }
    }

    /// Two of this module's `constants` that have the same Rust name are
    /// [`Error::ConflictingName`]; a procedure whose Rust name another procedure or a constant of
    /// the module has is returned, by path, with the reason it is skipped: functions and constants
    /// share Rust's value namespace.
    fn check_value_names(
        &self,
        constants: &[(&ConstantItem, (Constant, Option<String>))],
    ) -> Result<BTreeMap<String, String>, Error> {
        let constants: Vec<(String, String)> = constants
            .iter()
            .map(|(item, _)| {
                (item.path.to_string(), names::const_ident(item.path.last().unwrap_or_default()))
            })
            .collect();
        if let Some((first, second, name)) = names::duplicate(constants.iter().cloned()) {
            return Err(Error::ConflictingName {
                first,
                second,
                name,
            });
        }
        let procedures = self
            .procedures
            .iter()
            .map(|(item, _)| (item.path.to_string(), names::item_ident(item.name())));
        let mut holders: BTreeMap<String, Vec<String>> = BTreeMap::new();
        for (path, name) in constants.into_iter().chain(procedures.clone()) {
            holders.entry(name).or_default().push(path);
        }
        let mut collisions = BTreeMap::new();
        for (path, name) in procedures {
            let others: Vec<String> = holders[&name]
                .iter()
                .filter(|other| **other != path)
                .map(|other| format!("`{other}`"))
                .collect();
            if !others.is_empty() {
                let reason =
                    format!("its Rust name `{name}` is also that of {}", others.join(" and "));
                collisions.insert(path, reason);
            }
        }
        Ok(collisions)
    }
}

/// Writes the blank line between two items of a module, and none before the first.
#[derive(Default)]
struct Separator {
    started: bool,
}

impl Separator {
    fn next(&mut self, w: &mut Writer) {
        if core::mem::replace(&mut self.started, true) {
            w.blank();
        }
    }
}

/// `use <support>::{<names>};`, on one line if it fits, else with the names on a line of their
/// own, as rustfmt lays it out.
fn use_line(w: &mut Writer, support: &str, names: &[&str]) {
    let list = names.join(", ");
    let line = match names {
        [name] => format!("use {support}::{name};"),
        _ => format!("use {support}::{{{list}}};"),
    };
    // rustfmt breaks an import that ends in either of the last two columns, too.
    if w.indentation() + line.len() <= MAX_WIDTH - 2 {
        w.line(&line);
    } else {
        w.open_with(&format!("use {support}::{{"));
        w.line(&format!("{list},"));
        w.close_with("};");
    }
}

/// Write the type export `item` of the module `at`.
fn emit_type(
    w: &mut Writer,
    universe: &TypeUniverse<'_>,
    item: &TypeItem,
    at: &Path,
) -> Result<(), Error> {
    let name = names::type_ident(item.path.last().unwrap_or_default());
    let doc = format!("`{}`", item.path);
    let origin = item.path.to_string();
    match &item.ty {
        Type::Struct(st) => emit_struct(w, universe, &doc, &name, &st.get(), at, &origin),
        Type::Enum(en) => emit_enum(w, universe, &doc, &name, &en.get(), at, &origin),
        ty => {
            w.line(&format!("/// {doc}"));
            w.line(&format!("pub type {name} = {};", universe.rust_type(ty, at)?.text));
            Ok(())
        }
    }
}

/// Write a type the bindings declare themselves.
fn emit_local(w: &mut Writer, universe: &TypeUniverse<'_>, local: &LocalType) -> Result<(), Error> {
    let at = &local.module;
    let origin = format!("{at}::{}", local.name);
    match &local.ty {
        Type::Struct(st) => {
            emit_struct(w, universe, &local.doc, &local.name, &st.get(), at, &origin)
        }
        Type::Enum(en) => emit_enum(w, universe, &local.doc, &local.name, &en.get(), at, &origin),
        other => unreachable!("only structs and enums are declared as local types, not `{other}`"),
    }
}

/// Write the struct `name` (`st`) in the module `at`, with the doc line `doc`; `origin` names it
/// in an error.
///
/// It is written in the form [`layout::struct_form`] chooses, whose layout is the HIR layout; a
/// struct with no such form is [`Error::Unsupported`].
fn emit_struct(
    w: &mut Writer,
    universe: &TypeUniverse<'_>,
    doc: &str,
    name: &str,
    st: &StructType,
    at: &Path,
    origin: &str,
) -> Result<(), Error> {
    let form = layout::struct_form(st).map_err(|reason| Error::Unsupported {
        path: origin.to_string(),
        reason,
    })?;
    let mut fields = Vec::with_capacity(st.len());
    for (index, field) in st.fields().iter().enumerate() {
        let field_name = types::field_name(field, index);
        let ty = universe.field_type(&field.ty, at, form.words)?.text;
        fields.push(format!("pub {}: {ty},", names::item_ident(&field_name)));
    }
    w.line(&format!("/// {doc}"));
    w.line(&repr(form.repr));
    w.line(DERIVES);
    if fields.is_empty() {
        w.line(&format!("pub struct {name} {{}}"));
    } else {
        w.open(&format!("pub struct {name}"));
        for field in &fields {
            w.line(field);
        }
        w.close();
    }
    Ok(())
}

/// The `#[repr]` of a struct of the form `repr`, as HIR names it.
fn repr(repr: TypeRepr) -> String {
    match repr {
        TypeRepr::Default => "#[repr(C)]".to_string(),
        TypeRepr::Align(align) => format!("#[repr(C, align({align}))]"),
        TypeRepr::Packed(align) if align.get() == 1 => "#[repr(C, packed)]".to_string(),
        TypeRepr::Packed(align) => format!("#[repr(C, packed({align}))]"),
        TypeRepr::Transparent => "#[repr(transparent)]".to_string(),
    }
}

/// Write the enum `name` (`en`) and its `TryFrom` its discriminant, in the module `at`.
///
/// An enum with no Rust form ([`layout::enum_repr`]) is [`Error::Unsupported`]; `origin` names
/// it in the error.
fn emit_enum(
    w: &mut Writer,
    universe: &TypeUniverse<'_>,
    doc: &str,
    name: &str,
    en: &EnumType,
    at: &Path,
    origin: &str,
) -> Result<(), Error> {
    let discriminant = layout::enum_repr(en).map_err(|reason| Error::Unsupported {
        path: origin.to_string(),
        reason,
    })?;
    let repr = universe.rust_type(discriminant, at)?.text;
    let variants: Vec<(String, String)> = en
        .variants()
        .iter()
        .zip(en.discriminant_values())
        .map(|(variant, value)| {
            (names::variant_ident(&variant.name), discriminant_literal(value, discriminant))
        })
        .collect();

    w.line(&format!("/// {doc}"));
    w.line(&format!("#[repr({repr})]"));
    w.line(DERIVES);
    w.open(&format!("pub enum {name}"));
    for (variant, value) in &variants {
        w.line(&format!("{variant} = {value},"));
    }
    w.close();
    w.blank();
    // Prelude names in full: the module may define a type `Result` or a function `Ok`.
    w.open(&format!("impl ::core::convert::TryFrom<{repr}> for {name}"));
    w.line(&format!("type Error = {repr};"));
    w.blank();
    w.open(&format!("fn try_from(value: {repr}) -> {RESULT}<Self, Self::Error>"));
    w.open("match value");
    for (variant, value) in &variants {
        w.arm(value, &format!("{RESULT}::Ok(Self::{variant})"));
    }
    w.arm("_", &format!("{RESULT}::Err(value)"));
    w.close();
    w.close();
    w.close();
    Ok(())
}

/// A discriminant as a Rust literal of the integer type `ty`. HIR stores every discriminant as
/// the bits of a value of `ty`, zero-extended, so a negative one is reinterpreted.
fn discriminant_literal(value: u128, ty: &Type) -> String {
    match ty {
        Type::I8 => (value as u8 as i8).to_string(),
        Type::I16 => (value as u16 as i16).to_string(),
        Type::I32 => (value as u32 as i32).to_string(),
        Type::I64 => (value as u64 as i64).to_string(),
        _ => value.to_string(),
    }
}

/// A constant's Rust form.
enum Constant {
    /// An integer of the Rust type named.
    Int(&'static str, u64),
    /// A felt, as its canonical `u64`, which `FeltConstant::new` takes.
    Felt(u64),
    /// A word, as the canonical `u64`s of its elements, which `WordConstant::new` takes.
    Word([u64; 4]),
}

/// The Rust form of a constant's value, and the source of a hashed one (`word("…")`,
/// `event("…")`); `None` for a string, which has no Rust form.
///
/// A felt or word is not a `u64` (the Rust and VM representations of a felt differ), and no
/// `const fn` constructs a `Felt` on the Miden target, so it is held in the support module's
/// `FeltConstant`/`WordConstant`, whose `get()` makes the `Felt`/`Word`. `word("…")` and
/// `event("…")` are computed here, as the assembler computes them.
fn constant(value: &ConstantValue) -> Option<(Constant, Option<String>)> {
    let hashed =
        |kind: &str, string: &str| Some(format!("`{kind}(\"{}\")`", string.escape_debug()));
    Some(match value {
        ConstantValue::Int(int) => match int.inner() {
            IntValue::U8(v) => (Constant::Int("u8", u64::from(*v)), None),
            IntValue::U16(v) => (Constant::Int("u16", u64::from(*v)), None),
            IntValue::U32(v) => (Constant::Int("u32", u64::from(*v)), None),
            IntValue::Felt(felt) => (Constant::Felt(felt.as_canonical_u64()), None),
        },
        ConstantValue::Word(word) => {
            (Constant::Word(word.inner().0.map(|felt| felt.as_canonical_u64())), None)
        }
        ConstantValue::Hash(HashKind::Word, string) => {
            let word = hash_string_to_word(string.as_str());
            let elements = core::array::from_fn(|i| word[i].as_canonical_u64());
            (Constant::Word(elements), hashed("word", string.as_str()))
        }
        ConstantValue::Hash(HashKind::Event, string) => {
            let event = EventId::from_name(string.as_str()).as_felt().as_canonical_u64();
            (Constant::Felt(event), hashed("event", string.as_str()))
        }
        ConstantValue::String(_) => return None,
    })
}

/// Write the constant `item` of the module `at`, whose Rust form is `constant` and whose hashed
/// source, if any, is `source`.
fn emit_constant(
    w: &mut Writer,
    universe: &TypeUniverse<'_>,
    item: &ConstantItem,
    at: &Path,
    constant: Constant,
    source: Option<String>,
) {
    let name = names::const_ident(item.path.last().unwrap_or_default());
    w.line(&format!("/// `{}`", item.path));
    let (ty, value) = match constant {
        Constant::Int(ty, value) => (ty.to_string(), value.to_string()),
        Constant::Felt(value) => {
            let what = source.unwrap_or_else(|| "A felt".to_string());
            w.line("///");
            w.line(&format!("/// {what}: `{name}.get()` is the `Felt`."));
            let ty = universe.support_item("FeltConstant", at);
            let value = format!("{ty}::new({value})");
            (ty, value)
        }
        Constant::Word(elements) => {
            let what = source.unwrap_or_else(|| "A word".to_string());
            w.line("///");
            w.line(&format!("/// {what}: `{name}.get()` is the `Word`."));
            let ty = universe.support_item("WordConstant", at);
            let list = elements.map(|element| element.to_string());
            let array = format!("[{}]", list.join(", "));
            if array.len() > ARRAY_WIDTH {
                // The array goes on lines of its own, as rustfmt lays out a call whose one
                // argument is wider than an array may be on one line.
                w.open_with(&format!("pub const {name}: {ty} = {ty}::new(["));
                for element in &list {
                    w.line(&format!("{element},"));
                }
                w.close_with("]);");
                return;
            }
            let value = format!("{ty}::new({array})");
            (ty, value)
        }
    };
    let line = format!("pub const {name}: {ty} = {value};");
    if w.indentation() + line.len() <= MAX_WIDTH {
        w.line(&line);
    } else {
        w.line(&format!("pub const {name}: {ty} ="));
        w.continuation(&format!("{value};"));
    }
}

#[cfg(test)]
mod tests {
    use std::collections::BTreeMap;

    use miden_assembly_syntax::{Felt, debuginfo::Span, parser::WordValue};
    use midenc_package_interface::testing::{FIXTURE_SOURCE, assemble_fixture};

    use super::*;

    /// The text `emit_constant` writes for a constant named `name` (at the top level of the
    /// fixture's bindings).
    fn constant_text(name: &str, value: ConstantValue) -> String {
        let iface = PackageInterface::from_package(&assemble_fixture(
            "fixture",
            "::fixture",
            FIXTURE_SOURCE,
        ));
        let options = Options {
            root: "::fixture".into(),
            support: "crate::__support".into(),
            with: BTreeMap::new(),
        };
        let universe = TypeUniverse::new(&iface, &[], &options);
        let item = ConstantItem {
            path: Path::new(&format!("::fixture::{name}")).into(),
            value,
        };
        let (constant, source) = constant(&item.value).expect("not a string");
        let mut w = Writer::new();
        emit_constant(&mut w, &universe, &item, Path::new("::fixture"), constant, source);
        w.finish()
    }

    /// Lines are broken where rustfmt (with the workspace's settings) breaks them, so the
    /// generated text is what rustfmt would make of it: a constant at 101 columns, an array wider
    /// than 80, an import at 99.
    #[test]
    fn long_lines_break_where_rustfmt_breaks_them() {
        let felt = || ConstantValue::Int(Span::unknown(IntValue::Felt(Felt::new_unchecked(1234))));
        // `pub const : FeltConstant = FeltConstant::new(1234);` is 51 columns without the name.
        let fits = constant_text(&"A".repeat(49), felt());
        assert!(fits.ends_with("A: FeltConstant = FeltConstant::new(1234);\n"), "{fits}");
        let broken = constant_text(&"A".repeat(50), felt());
        assert!(
            broken.ends_with("A: FeltConstant =\n    FeltConstant::new(1234);\n"),
            "{broken}"
        );

        let word = |elements: [u64; 4]| {
            ConstantValue::Word(Span::unknown(WordValue(elements.map(Felt::new_unchecked))))
        };
        let short = constant_text("W", word([1, 2, 3, 4]));
        assert!(short.ends_with("pub const W: WordConstant = WordConstant::new([1, 2, 3, 4]);\n"));
        let wide = constant_text("W", word([u64::from(u32::MAX) << 30; 4]));
        assert!(
            wide.ends_with(
                "pub const W: WordConstant = WordConstant::new([\n    4611686017353646080,\n    \
                 4611686017353646080,\n    4611686017353646080,\n    4611686017353646080,\n]);\n"
            ),
            "{wide}"
        );

        // `use {support}::{ElementPtr, Felt};` is 25 columns without the support path.
        let mut w = Writer::new();
        use_line(&mut w, &"s".repeat(73), &["ElementPtr", "Felt"]);
        use_line(&mut w, &"s".repeat(74), &["ElementPtr", "Felt"]);
        let text = w.finish();
        let lines: Vec<&str> = text.lines().collect();
        assert_eq!(lines.len(), 4, "{text}");
        assert_eq!(lines[0].len(), 98);
        assert_eq!(lines[1], format!("use {}::{{", "s".repeat(74)));
        assert_eq!(lines[2], "    ElementPtr, Felt,");
        assert_eq!(lines[3], "};");
    }
}
