//! The stub source: the linker stubs of a package's bindable procedures.
//!
//! A binding's wrapper declares its procedure as an `extern "C"` function, resolved by name. The
//! stubs define those names, so that the Wasm module links: each is a weak function of the Wasm
//! carriers with a diverging body, which the Wasm frontend recognizes by its name and replaces
//! with the call to the Miden procedure. The text is the root of a `no_std` crate that the build
//! compiles into an archive.

use midenc_package_interface::{PackageInterface, ReturnStrategy, WasmScalar};

use crate::{
    Error, Skipped, names,
    render::{Returns, Writer},
};

/// The lines of the stub crate's root that follow the generated-from lines: what the stubs are,
/// and the crate's attributes.
const PREAMBLE: [&str; 9] = [
    "// Do not edit: regenerate from the package.",
    "//",
    "// Every stub is a weak definition of the symbol a binding declares, with a diverging body:",
    "// the Wasm frontend recognizes the name and lowers the call to the Miden procedure. Weak",
    "// linkage lets more than one crate carry stubs for the same package.",
    "#![no_std]",
    "#![feature(linkage, optimize_attribute)]",
    "// A stub is named after its procedure's path with `::` written `__`: not snake case.",
    "#![allow(non_snake_case)]",
];

/// The stub source of `package`: one stub for each bindable procedure, by path, except those the
/// bindings `skipped`, which declare no symbol.
///
/// Two stubs of one name (`a::b__c` and `a__b::c` are both `a__b__c`) are
/// [`Error::ConflictingName`].
pub(crate) fn stubs(package: &PackageInterface, skipped: &[Skipped]) -> Result<String, Error> {
    let skipped: Vec<&str> = skipped.iter().map(|skipped| skipped.path.as_str()).collect();
    let stubbed: Vec<_> = package
        .bindable()
        .filter(|(item, _)| !skipped.contains(&item.path.to_string().as_str()))
        .collect();
    let mut idents = Vec::with_capacity(stubbed.len());
    for (item, _) in &stubbed {
        idents.push((item.path.to_string(), names::stub_ident(&item.path)?));
    }
    if let Some((first, second, name)) = names::duplicate(idents) {
        return Err(Error::ConflictingName {
            first,
            second,
            name,
        });
    }
    let mut w = Writer::new();
    w.line(&format!(
        "// Generated by miden-sdk-bindgen: linker stubs for package `{}` {}.",
        AsRef::<str>::as_ref(&package.name),
        package.version
    ));
    w.line(&format!("// Dependency commitment: {}.", package.digest.to_hex()));
    for line in PREAMBLE {
        w.line(line);
    }
    for (item, lowered) in stubbed {
        w.blank();
        let link_name = names::link_name(&item.path).escape_default().to_string();
        w.line(&format!("#[unsafe(export_name = \"{link_name}\")]"));
        w.line("#[linkage = \"weak\"]");
        w.line("#[optimize(none)]");
        w.line("#[inline(never)]");
        let mut params: Vec<String> = lowered
            .params
            .iter()
            .enumerate()
            .map(|(index, param)| format!("_arg{index}: {}", wasm_type(&param.scalar)))
            .collect();
        let returns = match &lowered.ret {
            ReturnStrategy::Void => Returns::Nothing,
            ReturnStrategy::Direct(scalar) => Returns::Type(wasm_type(scalar).to_string()),
            ReturnStrategy::OutPointer(_) => {
                params.push("_ret: i32".to_string());
                Returns::Nothing
            }
        };
        let name = names::stub_ident(&item.path)?;
        w.signature(&format!("pub extern \"C\" fn {name}"), &params, &returns, true);
        w.line("unsafe { core::hint::unreachable_unchecked() }");
        w.close();
    }
    Ok(w.finish())
}

/// The Wasm type that carries `scalar`: `f32` for a felt, `i64` for a 64-bit integer, and `i32`
/// for everything else, addresses included.
fn wasm_type(scalar: &WasmScalar) -> &'static str {
    match scalar {
        WasmScalar::Felt => "f32",
        WasmScalar::I64 | WasmScalar::U64 => "i64",
        WasmScalar::I1
        | WasmScalar::I8
        | WasmScalar::U8
        | WasmScalar::I16
        | WasmScalar::U16
        | WasmScalar::I32
        | WasmScalar::U32
        | WasmScalar::Ptr(_) => "i32",
    }
}
