[package]
name = "{{crate_name}}"
version = "0.1.0"

[lib]
path = "src/lib.rs"
kind = "note"
namespace = "miden::{{crate_name}}::{{crate_name}}"

[dependencies]
miden-core = "*"
miden-protocol = "*"
# TODO: Add your account contract dependencies here
add-contract = { path = "../add-contract" }
