//! The WIT text writer.

use std::fmt::Write;

use crate::{
    CoreTypes, Skipped,
    types::{Decl, TypeSet},
};

/// One interface function, ready to print.
#[derive(Debug, Clone)]
pub struct Function {
    /// The WIT function name.
    pub name: String,
    /// The `@external-id` value: the procedure's export path.
    pub external_id: String,
    /// `(name, type)` per parameter.
    pub params: Vec<(String, String)>,
    /// The single result type, if any.
    pub result: Option<String>,
}

/// Everything one generated WIT document says.
pub struct Document<'a> {
    /// The masp package name, for the header.
    pub package_name: &'a str,
    /// The masp package version, for the header.
    pub package_version: String,
    /// The package's dependency commitment, for the header.
    pub commitment: String,
    /// The procedures left out, for the header.
    pub skipped: &'a [Skipped],
    /// The WIT package id.
    pub package_id: &'a str,
    /// The interface name.
    pub interface: &'a str,
    /// The world name.
    pub world: &'a str,
    /// Where the core types come from.
    pub core_types: &'a CoreTypes,
    /// The used and declared types.
    pub types: &'a TypeSet,
    /// The functions, in order.
    pub functions: &'a [Function],
}

/// The fully versioned id of the core-types interface, `<ns>:<name>/<interface>@<version>`.
fn core_types_id(core: &CoreTypes) -> String {
    match core.package.split_once('@') {
        Some((name, version)) => format!("{name}/{}@{version}", core.interface),
        None => format!("{}/{}", core.package, core.interface),
    }
}

/// Print `doc` as WIT text.
pub fn render(doc: &Document<'_>) -> String {
    let mut out = String::new();
    // `fmt::Write` for `String` never fails.
    let _ = write_document(&mut out, doc);
    out
}

fn write_document(out: &mut String, doc: &Document<'_>) -> std::fmt::Result {
    writeln!(
        out,
        "// Generated by midenc-package-wit from package `{}` {}.",
        doc.package_name, doc.package_version
    )?;
    writeln!(out, "// Dependency commitment: {}.", doc.commitment)?;
    if doc.skipped.is_empty() {
        writeln!(out, "// Skipped: none")?;
    }
    for skipped in doc.skipped {
        writeln!(out, "// Skipped: {}: {}", skipped.path, skipped.reason)?;
    }
    writeln!(out, "package {};", doc.package_id)?;
    writeln!(out)?;

    // Each block inside the interface, separated by blank lines.
    let mut blocks: Vec<String> = Vec::new();
    if !doc.types.core.is_empty() {
        let items: Vec<&str> = doc.types.core.iter().copied().collect();
        blocks.push(format!(
            "    use {}.{{{}}};\n",
            core_types_id(doc.core_types),
            items.join(", ")
        ));
    }
    for (name, decl) in &doc.types.locals {
        let mut block = String::new();
        let name = crate::naming::escape(name.clone());
        match decl {
            Decl::Record(fields) => {
                writeln!(block, "    record {name} {{")?;
                for (field, ty) in fields {
                    writeln!(block, "        {field}: {ty},")?;
                }
            }
            Decl::Enum(cases) => {
                writeln!(block, "    enum {name} {{")?;
                for case in cases {
                    writeln!(block, "        {case},")?;
                }
            }
        }
        writeln!(block, "    }}")?;
        blocks.push(block);
    }
    for function in doc.functions {
        let params: Vec<String> =
            function.params.iter().map(|(name, ty)| format!("{name}: {ty}")).collect();
        let result = function.result.as_ref().map(|ty| format!(" -> {ty}")).unwrap_or_default();
        blocks.push(format!(
            "    @external-id(\"{}\")\n    {}: func({}){result};\n",
            function.external_id,
            function.name,
            params.join(", ")
        ));
    }

    let interface = crate::naming::escape(doc.interface.to_owned());
    writeln!(out, "interface {interface} {{")?;
    out.push_str(&blocks.join("\n"));
    writeln!(out, "}}")?;
    writeln!(out)?;
    writeln!(out, "world {} {{", doc.world)?;
    writeln!(out, "    export {interface};")?;
    writeln!(out, "}}")
}
