//! Generation over fixture packages assembled from MASM.

use miden_mast_package::TargetType;
use midenc_package_interface::{PackageInterface, testing::assemble_fixture};

use super::*;

/// The SDK's core-types package, which every generated document `use`s.
const MIDEN_WIT: &str = include_str!("../../base-macros/wit/miden.wit");

/// A component exercising every mapping and skip rule.
const COMPONENT: &str = r#"
pub type Asset = struct { id: word, value: word }
pub type AccountId = struct { suffix: felt, prefix: felt }
pub type Nested = struct { owner: AccountId, amount: u64 }

pub enum NoteType : u8 {
    PRIVATE = 0,
    PUBLIC = 1,
}

pub enum Mode : u8 {
    FAST = 0,
    SLOW_AND_STEADY = 1,
}

pub enum Sparse : u8 {
    A = 0,
    B = 2,
}

@account_procedure
pub proc receive_asset(asset: Asset)
    dropw dropw
end

@account_procedure
pub proc swap(a: Asset, b: Asset) -> felt
    nop
end

@account_procedure
pub proc too_wide(a: Asset, b: Asset, c: felt)
    nop
end

@account_procedure
pub proc create_note(tag: u32, note_type: NoteType, recipient: word) -> u16
    nop
end

@account_procedure
pub proc owner() -> AccountId
    nop
end

@account_procedure
pub proc set_owner(id: AccountId, nested: Nested)
    nop
end

@account_procedure
pub proc set_mode(mode: Mode) -> i1
    nop
end

@account_procedure
pub proc sparse(s: Sparse)
    nop
end

@account_procedure
pub proc pair() -> (felt, felt)
    nop
end

@account_procedure
pub proc digest() -> word
    nop
end

@account_procedure
pub proc halves(x: [felt; 2])
    nop
end

@auth_script
pub proc auth_tx(salt: word)
    dropw
end

@account_procedure
pub proc untyped
    nop
end

pub proc helper(x: felt) -> felt
    nop
end
"#;

/// The module every fixture component's procedures live in.
const MODULE: &str = "miden::test::my_component";

/// The interface of an account-component package assembled from `source` in [`MODULE`].
fn component(source: &str) -> PackageInterface {
    let mut package = (*assemble_fixture("miden-test-my-component", MODULE, source)).clone();
    package.kind = TargetType::AccountComponent;
    PackageInterface::from_package(&package)
}

/// Parse `wit` next to the SDK's core types, check that every function carries an
/// `@external-id`, and return the `(name, external id)` of each function of `interface`.
fn parse(wit: &str, interface: &str) -> Vec<(String, String)> {
    let mut resolve = wit_parser::Resolve::new();
    resolve.push_str("miden.wit", MIDEN_WIT).expect("the core types parse");
    let package = resolve
        .push_str("generated.wit", wit)
        .unwrap_or_else(|err| panic!("generated WIT must parse: {err:?}\n{wit}"));
    let id = resolve.packages[package].interfaces[interface];
    resolve.interfaces[id]
        .functions
        .values()
        .map(|function| {
            let external_id = function
                .external_id
                .clone()
                .unwrap_or_else(|| panic!("`{}` has no external id", function.name));
            (function.name.clone(), external_id)
        })
        .collect()
}

#[test]
fn the_component_interface() {
    let iface = component(COMPONENT);
    let generated = generate(&iface, &Options::default()).unwrap();
    assert_eq!(generated.package_id, "miden:test-my-component@0.0.0");
    assert_eq!(generated.interface, "my-component");
    assert_eq!(generated.world, "my-component-world");

    let skipped: Vec<(&str, &str)> =
        generated.skipped.iter().map(|s| (s.path.as_str(), s.reason.as_str())).collect();
    assert_eq!(
        skipped,
        [
            (
                "miden::test::my_component::digest",
                "results occupy 4 stack elements; multi-element results of Miden Assembly \
                 components are not supported yet"
            ),
            ("miden::test::my_component::halves", "unsupported type `[felt; 2]`"),
            (
                "miden::test::my_component::owner",
                "results occupy 2 stack elements; multi-element results of Miden Assembly \
                 components are not supported yet"
            ),
            (
                "miden::test::my_component::pair",
                "results occupy 2 stack elements; multi-element results of Miden Assembly \
                 components are not supported yet"
            ),
            (
                "miden::test::my_component::sparse",
                "unsupported type `Sparse`: an enum with non-contiguous discriminants"
            ),
            (
                "miden::test::my_component::too_wide",
                "parameters flatten to 17 stack values, more than the 16 a direct call can pass"
            ),
            ("miden::test::my_component::untyped", "no typed signature"),
        ]
    );
    let digest = iface.digest.to_string();
    let expected = format!(
        r#"// Generated by midenc-package-wit from package `miden-test-my-component` 0.0.0.
// Dependency commitment: {digest}.
package miden:test-my-component@0.0.0;

/// Left out: `miden::test::my_component::digest`: results occupy 4 stack elements; multi-element results of Miden Assembly components are not supported yet
/// Left out: `miden::test::my_component::halves`: unsupported type `[felt; 2]`
/// Left out: `miden::test::my_component::owner`: results occupy 2 stack elements; multi-element results of Miden Assembly components are not supported yet
/// Left out: `miden::test::my_component::pair`: results occupy 2 stack elements; multi-element results of Miden Assembly components are not supported yet
/// Left out: `miden::test::my_component::sparse`: unsupported type `Sparse`: an enum with non-contiguous discriminants
/// Left out: `miden::test::my_component::too_wide`: parameters flatten to 17 stack values, more than the 16 a direct call can pass
/// Left out: `miden::test::my_component::untyped`: no typed signature
interface my-component {{
    use miden:base/core-types@1.0.0.{{asset, felt, note-type, word}};

    enum mode {{
        fast,
        slow-and-steady,
    }}

    record account-id {{
        suffix: felt,
        prefix: felt,
    }}

    record nested {{
        owner: account-id,
        amount: u64,
    }}

    @external-id("miden::test::my_component::auth_tx")
    auth-tx: func(arg0: word);

    @external-id("miden::test::my_component::create_note")
    create-note: func(arg0: u32, note-type: note-type, arg2: word) -> u16;

    @external-id("miden::test::my_component::receive_asset")
    receive-asset: func(asset: asset);

    @external-id("miden::test::my_component::set_mode")
    set-mode: func(mode: mode) -> bool;

    @external-id("miden::test::my_component::set_owner")
    set-owner: func(account-id: account-id, nested: nested);

    @external-id("miden::test::my_component::swap")
    swap: func(asset: asset, asset2: asset) -> felt;
}}

world my-component-world {{
    export my-component;
}}
"#
    );
    assert_eq!(generated.wit, expected);

    let functions = parse(&generated.wit, "my-component");
    assert_eq!(functions.len(), 6);
    assert!(functions.contains(&(
        "receive-asset".to_owned(),
        "miden::test::my_component::receive_asset".to_owned()
    )));
}

#[test]
fn an_account_id_in_core_order_uses_the_core_type() {
    let iface = component(
        r#"
pub type AccountId = struct { prefix: felt, suffix: felt }

@account_procedure
pub proc set_owner(id: AccountId)
    drop drop
end
"#,
    );
    let generated = generate(&iface, &Options::default()).unwrap();
    assert!(generated.skipped.is_empty());
    assert!(generated.wit.contains("/// Left out: none\ninterface my-component {\n"));
    assert!(generated.wit.contains("use miden:base/core-types@1.0.0.{account-id};"));
    assert!(generated.wit.contains("set-owner: func(account-id: account-id);"));
    assert!(!generated.wit.contains("record"));
    parse(&generated.wit, "my-component");
}

#[test]
fn a_function_without_parameters() {
    let iface = component(
        r#"
@account_procedure
pub proc ping()
    nop
end
"#,
    );
    let generated = generate(&iface, &Options::default()).unwrap();
    assert!(!generated.wit.contains("use "), "no core item is used");
    assert!(generated.wit.contains("    ping: func();\n"));
    parse(&generated.wit, "my-component");
}

#[test]
fn only_account_components_have_an_interface() {
    let package = assemble_fixture("miden-test-my-component", MODULE, COMPONENT);
    let iface = PackageInterface::from_package(&package);
    assert!(matches!(
        generate(&iface, &Options::default()),
        Err(Error::NotAComponent(TargetType::Library))
    ));
}

#[test]
fn a_component_needs_interface_procedures() {
    let iface = component(
        r#"
pub proc helper(x: felt) -> felt
    nop
end

@note_script
pub proc run_note()
    nop
end
"#,
    );
    assert!(matches!(
        generate(&iface, &Options::default()),
        Err(Error::NoInterfaceProcedures)
    ));
}

#[test]
fn a_quoted_export_path_is_skipped() {
    let iface = component(
        r#"
@account_procedure
pub proc ping()
    nop
end

@account_procedure
pub proc "with-dash"()
    nop
end
"#,
    );
    let generated = generate(&iface, &Options::default()).unwrap();
    assert_eq!(generated.skipped.len(), 1, "{:?}", generated.skipped);
    assert!(generated.skipped[0].path.contains('"'), "{:?}", generated.skipped);
    assert!(
        generated.skipped[0]
            .reason
            .starts_with("the export path is not a Miden procedure path"),
        "{:?}",
        generated.skipped
    );
    parse(&generated.wit, "my-component");
}

#[test]
fn names_without_a_wit_form_are_skipped() {
    let iface = component(
        r#"
@account_procedure
pub proc ping()
    nop
end

@account_procedure
pub proc _1()
    nop
end

@account_procedure
pub proc fpi_call()
    nop
end
"#,
    );
    let generated = generate(&iface, &Options::default()).unwrap();
    let skipped: Vec<(&str, &str)> =
        generated.skipped.iter().map(|s| (s.path.as_str(), s.reason.as_str())).collect();
    assert_eq!(
        skipped,
        [
            (
                "miden::test::my_component::_1",
                "the procedure name `_1` has no WIT name (derived `1`)"
            ),
            (
                "miden::test::my_component::fpi_call",
                "the function name `fpi-call` starts with `fpi-`, which the SDK reserves for its \
                 foreign procedure call imports"
            ),
        ]
    );
    assert!(
        generated.wit.contains(
            "/// Left out: `miden::test::my_component::_1`: the procedure name `_1` has no WIT \
             name (derived `1`)\n"
        ),
        "{}",
        generated.wit
    );
    assert_eq!(parse(&generated.wit, "my-component").len(), 1);
}

/// The generation error for a package named `package_name` whose procedures live in `module`.
fn namespace_error(package_name: &str, module: &str) -> String {
    let mut package = (*assemble_fixture(
        package_name,
        module,
        "@account_procedure\npub proc ping()\n    nop\nend\n",
    ))
    .clone();
    package.kind = TargetType::AccountComponent;
    match generate(&PackageInterface::from_package(&package), &Options::default()) {
        Err(Error::Namespace(reason)) => reason,
        other => panic!("expected a namespace error, got {other:?}"),
    }
}

#[test]
fn keyword_package_and_interface_names_are_rejected() {
    // The SDK macros write the package id and the interface name back into WIT text and Rust
    // module paths unescaped, so a keyword there has no usable spelling.
    assert_eq!(
        namespace_error("miden-test-my-component", "miden::test::record"),
        "the module `record` is a WIT keyword"
    );
    assert_eq!(
        namespace_error("miden-test-my-component", "miden::test::match"),
        "the module `match` is a Rust keyword"
    );
    assert_eq!(
        namespace_error("list", "miden::test::my_component"),
        "the package name `list` is a WIT keyword"
    );
    assert_eq!(
        namespace_error("use-foo", "use::test::my_component"),
        "the namespace `use` is a WIT keyword"
    );
}

#[test]
fn rust_keywords_wit_bindgen_does_not_escape_are_skipped() {
    let iface = component(
        r#"
pub type Seed = struct { gen: felt }

@account_procedure
pub proc ping()
    nop
end

@account_procedure
pub proc gen()
    nop
end

@account_procedure
pub proc reseed(seed: Seed)
    drop
end
"#,
    );
    let generated = generate(&iface, &Options::default()).unwrap();
    let skipped: Vec<(&str, &str)> =
        generated.skipped.iter().map(|s| (s.path.as_str(), s.reason.as_str())).collect();
    assert_eq!(
        skipped,
        [
            (
                "miden::test::my_component::gen",
                "the procedure name `gen` would be the Rust keyword `gen` in the generated \
                 bindings, which wit-bindgen does not escape"
            ),
            (
                "miden::test::my_component::reseed",
                "unsupported type `Seed`: field `gen` would be the Rust keyword `gen` in the \
                 generated bindings, which wit-bindgen does not escape"
            ),
        ]
    );
    assert_eq!(parse(&generated.wit, "my-component").len(), 1);
}

#[test]
fn a_function_named_like_a_type_is_skipped_not_its_users() {
    let iface = component(
        r#"
pub type Asset = struct { id: word, value: word }

@account_procedure
pub proc asset() -> felt
    nop
end

@account_procedure
pub proc receive_asset(asset: Asset)
    dropw dropw
end
"#,
    );
    let generated = generate(&iface, &Options::default()).unwrap();
    let skipped: Vec<(&str, &str)> =
        generated.skipped.iter().map(|s| (s.path.as_str(), s.reason.as_str())).collect();
    assert_eq!(
        skipped,
        [(
            "miden::test::my_component::asset",
            "function `asset` has the name of a type in the interface"
        )]
    );
    assert_eq!(
        parse(&generated.wit, "my-component"),
        [(
            "receive-asset".to_owned(),
            "miden::test::my_component::receive_asset".to_owned()
        )]
    );
}

#[test]
fn a_component_whose_every_procedure_is_left_out_has_no_interface() {
    let iface = component(
        r#"
@account_procedure
pub proc digest() -> word
    nop
end

@account_procedure
pub proc untyped
    nop
end
"#,
    );
    let err = generate(&iface, &Options::default()).unwrap_err();
    let Error::EverythingSkipped(skipped) = &err else {
        panic!("expected every procedure to be left out, got {err:?}");
    };
    assert_eq!(skipped.len(), 2);
    assert_eq!(
        err.to_string(),
        "every interface procedure is left out:\n  `miden::test::my_component::digest`: results \
         occupy 4 stack elements; multi-element results of Miden Assembly components are not \
         supported yet\n  `miden::test::my_component::untyped`: no typed signature"
    );
}

#[test]
fn only_account_procedures_and_auth_scripts_form_the_interface() {
    let iface = component(
        r#"
@account_procedure
pub proc ping()
    nop
end

@note_script
pub proc run_note()
    nop
end

@transaction_script
pub proc run_tx()
    nop
end
"#,
    );
    let generated = generate(&iface, &Options::default()).unwrap();
    assert!(generated.skipped.is_empty(), "{:?}", generated.skipped);
    let functions = parse(&generated.wit, "my-component");
    assert_eq!(functions, [("ping".to_owned(), "miden::test::my_component::ping".to_owned())]);
}

#[test]
fn a_u64_result_is_left_out() {
    let iface = component(
        r#"
@account_procedure
pub proc ping()
    nop
end

@account_procedure
pub proc nonce() -> u64
    nop
end
"#,
    );
    let generated = generate(&iface, &Options::default()).unwrap();
    let skipped: Vec<(&str, &str)> =
        generated.skipped.iter().map(|s| (s.path.as_str(), s.reason.as_str())).collect();
    assert_eq!(
        skipped,
        [(
            "miden::test::my_component::nonce",
            "results occupy 2 stack elements; multi-element results of Miden Assembly components \
             are not supported yet"
        )]
    );
}

#[test]
fn only_types_of_kept_functions_shadow_a_function() {
    // `z_set_mode` alone would declare `mode`, but its local `account-id` conflicts with the core
    // one `set_owner` uses, so it is left out and `mode` stays a function name.
    let iface = component(
        r#"
pub type Account_Id = struct { prefix: felt, suffix: felt }
pub type AccountId = struct { suffix: felt, prefix: felt }

pub enum Mode : u8 {
    A = 0,
    B = 1,
}

@account_procedure
pub proc mode() -> u32
    nop
end

@account_procedure
pub proc set_owner(id: Account_Id)
    drop drop
end

@account_procedure
pub proc z_set_mode(id: AccountId, m: Mode)
    drop drop drop
end
"#,
    );
    let generated = generate(&iface, &Options::default()).unwrap();
    let skipped: Vec<(&str, &str)> =
        generated.skipped.iter().map(|s| (s.path.as_str(), s.reason.as_str())).collect();
    assert_eq!(
        skipped,
        [(
            "miden::test::my_component::z_set_mode",
            "conflicting definitions of type `account-id` in one interface"
        )]
    );
    assert_eq!(
        parse(&generated.wit, "my-component"),
        [
            ("mode".to_owned(), "miden::test::my_component::mode".to_owned()),
            ("set-owner".to_owned(), "miden::test::my_component::set_owner".to_owned()),
        ]
    );
}
