//! Bindings generated from the Miden package manifests, one module per package.
//!
//! Regenerated by `tests/generated.rs` (`UPDATE_BINDINGS=1`); never edited by hand.

/// The core library (`miden-core`), mounted at its root `::miden::core`.
// Generated names follow MASM's spelling, wrappers take one parameter per operand, and the
// generated items carry the MASM path as their doc rather than prose.
#[allow(non_camel_case_types, non_snake_case, clippy::too_many_arguments, missing_docs)]
#[rustfmt::skip]
pub mod core;
