// Generated by miden-sdk-bindgen: linker stubs for package `miden-protocol` 0.17.0.
// Dependency commitment: 0x59f743fbcdb9da4295f6f26446780e87be2319e806de6e1272d55c0997c1ce9f.
// Do not edit: regenerate from the package.
//
// Every stub is a weak definition of the symbol a binding declares, with a diverging body:
// the Wasm frontend recognizes the name and lowers the call to the Miden procedure. Weak
// linkage lets more than one crate carry stubs for the same package.
#![no_std]
#![feature(linkage, optimize_attribute)]
// A stub is named after its procedure's path with `::` written `__`: not snake case.
#![allow(non_snake_case)]

#[unsafe(export_name = "miden::protocol::account_id::eq")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__account_id__eq(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::account_id::eqz")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__account_id__eqz(_arg0: f32, _arg1: f32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::account_id::shape_suffix")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__account_id__shape_suffix(_arg0: f32) -> f32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::account_id::testz")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__account_id__testz(_arg0: f32, _arg1: f32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::account_id::validate_structure")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__account_id__validate_structure(_arg0: f32, _arg1: f32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_account::compute_storage_commitment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_account__compute_storage_commitment(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_account::get_asset")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_account__get_asset(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_account::get_code_commitment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_account__get_code_commitment(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_account::get_id")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_account__get_id(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_account::get_item")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_account__get_item(_arg0: f32, _arg1: f32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_account::get_map_item")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_account__get_map_item(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_account::get_nonce")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_account__get_nonce() -> f32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_account::get_num_procedures")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_account__get_num_procedures() -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_account::get_procedure_root")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_account__get_procedure_root(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_account::get_vault_root")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_account__get_vault_root(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_account::has_asset")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_account__has_asset(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_account::has_procedure")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_account__has_procedure(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_account::has_storage_slot")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_account__has_storage_slot(_arg0: f32, _arg1: f32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::find_attachment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__find_attachment(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::get_asset")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__get_asset(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::get_attachments_commitment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__get_attachments_commitment(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::get_bounded_storage")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__get_bounded_storage(_arg0: i32, _arg1: i32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::get_initial_assets")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__get_initial_assets(_arg0: i32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::get_initial_assets_info")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__get_initial_assets_info(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::get_initial_num_assets")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__get_initial_num_assets() -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::get_metadata")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__get_metadata(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::get_note_id")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__get_note_id(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::get_recipient")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__get_recipient(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::get_script_root")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__get_script_root(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::get_sender")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__get_sender(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::get_serial_number")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__get_serial_number(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::get_storage")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__get_storage(_arg0: i32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::get_storage_info")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__get_storage_info(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::is_private")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__is_private() -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::is_public")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__is_public() -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::remove_all_assets")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__remove_all_assets(_arg0: i32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::remove_asset")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__remove_asset(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::write_attachment_commitments_to_memory")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__write_attachment_commitments_to_memory(
    _arg0: i32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::write_attachment_to_memory")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__write_attachment_to_memory(
    _arg0: i32,
    _arg1: i32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::active_note::write_storage_to_memory")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__active_note__write_storage_to_memory(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: i32,
    _arg5: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::asset::fungible_value_into_amount_unchecked")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__asset__fungible_value_into_amount_unchecked(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
) -> f32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::asset::id_into_asset_class")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__asset__id_into_asset_class(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::asset::id_into_composition")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__asset__id_into_composition(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::asset::id_into_faucet_id")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__asset__id_into_faucet_id(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::asset::id_to_asset_class")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__asset__id_to_asset_class(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::asset::id_to_composition")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__asset__id_to_composition(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::asset::id_to_faucet_id")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__asset__id_to_faucet_id(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::asset::load")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__asset__load(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::asset::store")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__asset__store(
    _arg0: i32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _arg8: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::faucet::burn")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__faucet__burn(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::faucet::mint")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__faucet__mint(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::input_note::find_attachment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__input_note__find_attachment(_arg0: i32, _arg1: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::input_note::find_note")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__input_note__find_note(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::input_note::get_asset")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__input_note__get_asset(_arg0: i32, _arg1: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::input_note::get_attachments_commitment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__input_note__get_attachments_commitment(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::input_note::get_initial_assets")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__input_note__get_initial_assets(_arg0: i32, _arg1: i32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::input_note::get_initial_assets_info")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__input_note__get_initial_assets_info(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::input_note::get_initial_num_assets")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__input_note__get_initial_num_assets(_arg0: i32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::input_note::get_metadata")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__input_note__get_metadata(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::input_note::get_note_id")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__input_note__get_note_id(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::input_note::get_recipient")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__input_note__get_recipient(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::input_note::get_script_root")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__input_note__get_script_root(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::input_note::get_sender")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__input_note__get_sender(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::input_note::get_serial_number")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__input_note__get_serial_number(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::input_note::get_storage_info")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__input_note__get_storage_info(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::input_note::remove_all_assets")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__input_note__remove_all_assets(_arg0: i32, _arg1: i32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::input_note::remove_asset")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__input_note__remove_asset(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _arg8: i32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::input_note::write_attachment_commitments_to_memory")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__input_note__write_attachment_commitments_to_memory(
    _arg0: i32,
    _arg1: i32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::input_note::write_attachment_to_memory")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__input_note__write_attachment_to_memory(
    _arg0: i32,
    _arg1: i32,
    _arg2: i32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::add_asset")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__add_asset(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::compute_commitment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__compute_commitment(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::compute_delta_commitment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__compute_delta_commitment(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::get_code_upgrade_commitment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__get_code_upgrade_commitment(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::get_id")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__get_id(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::get_initial_asset")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__get_initial_asset(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::get_initial_commitment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__get_initial_commitment(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::get_initial_item")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__get_initial_item(
    _arg0: f32,
    _arg1: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::get_initial_map_item")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__get_initial_map_item(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::get_initial_storage_commitment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__get_initial_storage_commitment(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::get_initial_vault_root")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__get_initial_vault_root(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::has_initial_asset")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__has_initial_asset(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::has_state_changed")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__has_state_changed() -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::incr_nonce")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__incr_nonce() -> f32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::remove_asset")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__remove_asset(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::set_item")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__set_item(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::set_map_item")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__set_map_item(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _arg8: f32,
    _arg9: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::upgrade")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__upgrade(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::native_account::was_procedure_called")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__native_account__was_procedure_called(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::note::compute_and_store_recipient")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__note__compute_and_store_recipient(
    _arg0: i32,
    _arg1: i32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _arg8: f32,
    _arg9: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::note::compute_recipient")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__note__compute_recipient(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _arg8: f32,
    _arg9: f32,
    _arg10: f32,
    _arg11: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::note::compute_storage_commitment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__note__compute_storage_commitment(
    _arg0: i32,
    _arg1: i32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::note::find_attachment_idx")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__note__find_attachment_idx(
    _arg0: i32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::note::metadata_into_attachment_schemes")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__note__metadata_into_attachment_schemes(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::note::metadata_into_note_type")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__note__metadata_into_note_type(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::note::metadata_into_sender")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__note__metadata_into_sender(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::note::metadata_into_tag")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__note__metadata_into_tag(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::output_note::add_asset")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__output_note__add_asset(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _arg8: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::output_note::add_attachment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__output_note__add_attachment(
    _arg0: i32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::output_note::add_attachment_from_memory")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__output_note__add_attachment_from_memory(
    _arg0: i32,
    _arg1: i32,
    _arg2: i32,
    _arg3: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::output_note::add_word_attachment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__output_note__add_word_attachment(
    _arg0: i32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::output_note::compute_note_id")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__output_note__compute_note_id(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::output_note::create")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__output_note__create(
    _arg0: i32,
    _arg1: i32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::output_note::find_attachment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__output_note__find_attachment(_arg0: i32, _arg1: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::output_note::get_assets")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__output_note__get_assets(_arg0: i32, _arg1: i32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::output_note::get_assets_info")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__output_note__get_assets_info(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::output_note::get_attachments_commitment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__output_note__get_attachments_commitment(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::output_note::get_metadata")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__output_note__get_metadata(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::output_note::get_recipient")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__output_note__get_recipient(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::output_note::is_sealed")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__output_note__is_sealed(_arg0: i32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::output_note::seal")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__output_note__seal(_arg0: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::output_note::write_attachment_commitments_to_memory")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__output_note__write_attachment_commitments_to_memory(
    _arg0: i32,
    _arg1: i32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::output_note::write_attachment_to_memory")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__output_note__write_attachment_to_memory(
    _arg0: i32,
    _arg1: i32,
    _arg2: i32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::tx::compute_fee")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__tx__compute_fee(
    _arg0: i32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
) -> f32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::tx::get_block_commitment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__tx__get_block_commitment(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::tx::get_block_timestamp")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__tx__get_block_timestamp() -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::tx::get_expiration_block_delta")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__tx__get_expiration_block_delta() -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::tx::get_fee_asset_id")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__tx__get_fee_asset_id(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::tx::get_input_notes_commitment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__tx__get_input_notes_commitment(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::tx::get_num_input_notes")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__tx__get_num_input_notes() -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::tx::get_num_output_notes")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__tx__get_num_output_notes() -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::tx::get_output_notes_commitment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__tx__get_output_notes_commitment(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::tx::get_reference_block_commitment")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__tx__get_reference_block_commitment(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::tx::get_reference_block_number")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__tx__get_reference_block_number() -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::tx::get_tx_script_root")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__tx__get_tx_script_root(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::protocol::tx::update_expiration_block_delta")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__protocol__tx__update_expiration_block_delta(_arg0: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}
