// Generated by miden-sdk-bindgen: linker stubs for package `miden-standards` 0.17.0.
// Dependency commitment: 0x5b5f925c20ac209a4a0a278879dad063f3ccf3024c25617bd75e26ef3435b843.
// Do not edit: regenerate from the package.
//
// Every stub is a weak definition of the symbol a binding declares, with a diverging body:
// the Wasm frontend recognizes the name and lowers the call to the Miden procedure. Weak
// linkage lets more than one crate carry stubs for the same package.
#![no_std]
#![feature(linkage, optimize_attribute)]
// A stub is named after its procedure's path with `::` written `__`: not snake case.
#![allow(non_snake_case)]

#[unsafe(export_name = "miden::standards::access::authority::assert_authorized")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__access__authority__assert_authorized() {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::access::ownable2step::assert_sender_is_owner")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__access__ownable2step__assert_sender_is_owner() {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::access::ownable2step::is_sender_owner")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__access__ownable2step__is_sender_owner() -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::access::pausable::assert_not_paused")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__access__pausable__assert_not_paused() {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::access::pausable::assert_paused")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__access__pausable__assert_paused() {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::access::pausable::pause")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__access__pausable__pause() {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::access::pausable::unpause")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__access__pausable__unpause() {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::access::rbac::assert_sender_has_role")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__access__rbac__assert_sender_has_role(_arg0: f32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::access::rbac::assert_sender_is_admin")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__access__rbac__assert_sender_is_admin() {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::access::role_symbol::validate_admin_role_symbol")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__access__role_symbol__validate_admin_role_symbol(_arg0: f32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::access::role_symbol::validate_encoding")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__access__role_symbol__validate_encoding(_arg0: f32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::assets::asset_amount::pow10")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__assets__asset_amount__pow10(_arg0: i32) -> f32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::assets::asset_amount::reverse_limbs_and_change_byte_endianness")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__assets__asset_amount__reverse_limbs_and_change_byte_endianness(
    _arg0: i32,
    _arg1: i32,
    _arg2: i32,
    _arg3: i32,
    _arg4: i32,
    _arg5: i32,
    _arg6: i32,
    _arg7: i32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::assets::asset_amount::scale_asset_amount_to_u256")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__assets__asset_amount__scale_asset_amount_to_u256(
    _arg0: f32,
    _arg1: i32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::assets::asset_amount::verify_u128_to_asset_amount_conversion")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__assets__asset_amount__verify_u128_to_asset_amount_conversion(
    _arg0: i32,
    _arg1: i32,
    _arg2: i32,
    _arg3: i32,
    _arg4: i32,
    _arg5: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::assets::asset_amount::verify_u256_to_asset_amount_conversion")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__assets__asset_amount__verify_u256_to_asset_amount_conversion(
    _arg0: i32,
    _arg1: i32,
    _arg2: i32,
    _arg3: i32,
    _arg4: i32,
    _arg5: i32,
    _arg6: i32,
    _arg7: i32,
    _arg8: i32,
    _arg9: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::assets::fungible_asset::create")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__assets__fungible_asset__create(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::assets::fungible_asset::create_id")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__assets__fungible_asset__create_id(
    _arg0: f32,
    _arg1: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::assets::fungible_asset::create_value")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__assets__fungible_asset__create_value(_arg0: f32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::assets::fungible_asset::get_active_account_balance")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__assets__fungible_asset__get_active_account_balance(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
) -> f32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::assets::fungible_asset::get_initial_native_account_balance")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__assets__fungible_asset__get_initial_native_account_balance(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
) -> f32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::assets::fungible_asset::to_amount_unchecked")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__assets__fungible_asset__to_amount_unchecked(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::assets::fungible_asset::validate")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__assets__fungible_asset__validate(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::assets::fungible_asset::value_into_amount")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__assets__fungible_asset__value_into_amount(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
) -> f32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::assets::fungible_asset::value_into_amount_unchecked")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__assets__fungible_asset__value_into_amount_unchecked(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
) -> f32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::assets::non_fungible_asset::create")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__assets__non_fungible_asset__create(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::assets::non_fungible_asset::validate")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__assets__non_fungible_asset__validate(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::assets::non_fungible_asset::value_into_asset_class")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__assets__non_fungible_asset__value_into_asset_class(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::attachments::network_account_target::active_account_matches_target_account")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__attachments__network_account_target__active_account_matches_target_account()
-> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::attachments::network_account_target::into_target_id")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__attachments__network_account_target__into_target_id(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::attachments::network_account_target::is_network_account_target")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__attachments__network_account_target__is_network_account_target(
    _arg0: i32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::attachments::network_account_target::new")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__attachments__network_account_target__new(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::eip712_transaction_summary::compute_signature_key")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__eip712_transaction_summary__compute_signature_key(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::eip712_transaction_summary::verify")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__eip712_transaction_summary__verify(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::guardian::assert_rotation_policy")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__guardian__assert_rotation_policy() -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::guardian::get_guardian_public_key")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__guardian__get_guardian_public_key(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::guardian::verify_signature")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__guardian__verify_signature(
    _arg0: i32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::multisig::apply_approval_expiration")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__multisig__apply_approval_expiration(_arg0: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::multisig::assert_approval_not_expired")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__multisig__assert_approval_not_expired(
    _arg0: i32,
    _arg1: i32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::multisig::assert_not_approver_public_key")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__multisig__assert_not_approver_public_key(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::multisig::assert_num_approvers_in_bounds")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__multisig__assert_num_approvers_in_bounds(_arg0: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::multisig::assert_threshold_is_reachable")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__multisig__assert_threshold_is_reachable(
    _arg0: i32,
    _arg1: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::multisig::assert_unique_approver_public_keys")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__multisig__assert_unique_approver_public_keys(_arg0: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::multisig::auth_tx")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__multisig__auth_tx(
    _arg0: i32,
    _arg1: i32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::multisig::cleanup_pubkey_and_scheme_id_mapping")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__multisig__cleanup_pubkey_and_scheme_id_mapping(
    _arg0: i32,
    _arg1: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::multisig::get_initial_threshold_and_num_approvers")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__multisig__get_initial_threshold_and_num_approvers(
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::multisig::record_and_assert_new_tx")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__multisig__record_and_assert_new_tx(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::multisig::resolve_auth_args")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__multisig__resolve_auth_args(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::multisig_smart::auth_tx")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__multisig_smart__auth_tx(
    _arg0: i32,
    _arg1: i32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::multisig_smart::enforce_note_restrictions")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__multisig_smart__enforce_note_restrictions(_arg0: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::multisig_smart::get_procedure_policy")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__multisig_smart__get_procedure_policy(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::network_account::assert_transaction_allowed")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__network_account__assert_transaction_allowed() {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::network_account::get_sponsor_at_most_collected_fees")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__network_account__get_sponsor_at_most_collected_fees()
-> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::note_script_allowlist::add_note_script")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__note_script_allowlist__add_note_script(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::note_script_allowlist::assert_all_input_notes_allowed")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__note_script_allowlist__assert_all_input_notes_allowed(
    _arg0: f32,
    _arg1: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::note_script_allowlist::remove_note_script")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__note_script_allowlist__remove_note_script(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::signature::assert_supported_scheme")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__signature__assert_supported_scheme(_arg0: f32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::signature::assert_supported_scheme_word")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__signature__assert_supported_scheme_word(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::signature::authenticate_transaction")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__signature__authenticate_transaction(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::signature::authenticate_transaction_with_user_params")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__signature__authenticate_transaction_with_user_params(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _arg8: f32,
    _arg9: f32,
    _arg10: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::signature::create_approver_map_key")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__signature__create_approver_map_key(
    _arg0: i32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::signature::estimate_authentication_cycles")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__signature__estimate_authentication_cycles(
    _arg0: i32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::signature::estimate_multisig_authentication_cycles")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__signature__estimate_multisig_authentication_cycles(
    _arg0: i32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::signature::is_supported_scheme")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__signature__is_supported_scheme(_arg0: f32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::signature::verify_signatures")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__signature__verify_signatures(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: i32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _arg8: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::tx_policy::assert_no_input_notes")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__tx_policy__assert_no_input_notes() {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::tx_policy::assert_no_output_notes")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__tx_policy__assert_no_output_notes() {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::tx_policy::assert_only_one_non_auth_procedure_called")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__tx_policy__assert_only_one_non_auth_procedure_called() {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::tx_script_allowlist::add_tx_script")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__tx_script_allowlist__add_tx_script(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::tx_script_allowlist::assert_tx_script_allowed")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__tx_script_allowlist__assert_tx_script_allowed(
    _arg0: f32,
    _arg1: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::auth::tx_script_allowlist::remove_tx_script")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__auth__tx_script_allowlist__remove_tx_script(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::data_structures::array::get")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__data_structures__array__get(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::data_structures::array::set")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__data_structures__array__set(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::data_structures::double_word_array::get")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__data_structures__double_word_array__get(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::data_structures::double_word_array::set")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__data_structures__double_word_array__set(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _arg8: f32,
    _arg9: f32,
    _arg10: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::expiration::apply_default")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__expiration__apply_default() {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::faucets::get_mutability_config_word")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__faucets__get_mutability_config_word(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::faucets::policies::policy_manager::execute_burn_policy")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__faucets__policies__policy_manager__execute_burn_policy(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::faucets::policies::policy_manager::execute_mint_policy")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__faucets__policies__policy_manager__execute_mint_policy(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: i32,
    _arg5: i32,
    _arg6: f32,
    _arg7: f32,
    _arg8: f32,
    _arg9: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::faucets::policies::transfer::allowlist::allow_account")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__faucets__policies__transfer__allowlist__allow_account(
    _arg0: f32,
    _arg1: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::faucets::policies::transfer::allowlist::assert_allowed")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__faucets__policies__transfer__allowlist__assert_allowed(
    _arg0: f32,
    _arg1: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::faucets::policies::transfer::allowlist::disallow_account")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__faucets__policies__transfer__allowlist__disallow_account(
    _arg0: f32,
    _arg1: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::faucets::policies::transfer::allowlist::is_allowed")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__faucets__policies__transfer__allowlist__is_allowed(
    _arg0: f32,
    _arg1: f32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::faucets::policies::transfer::blocklist::assert_not_blocked")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__faucets__policies__transfer__blocklist__assert_not_blocked(
    _arg0: f32,
    _arg1: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::faucets::policies::transfer::blocklist::block_account")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__faucets__policies__transfer__blocklist__block_account(
    _arg0: f32,
    _arg1: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::faucets::policies::transfer::blocklist::is_blocked")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__faucets__policies__transfer__blocklist__is_blocked(
    _arg0: f32,
    _arg1: f32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::faucets::policies::transfer::blocklist::unblock_account")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__faucets__policies__transfer__blocklist__unblock_account(
    _arg0: f32,
    _arg1: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::fee::apply_cycle_margins")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__fee__apply_cycle_margins(_arg0: f32) -> f32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::fee::convert_amount")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__fee__convert_amount(_arg0: f32, _arg1: f32, _arg2: f32) -> f32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::fee::create_and_fund_fee_note")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__fee__create_and_fund_fee_note(
    _arg0: i32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _arg8: f32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::fee::load_conversion_info")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__fee__load_conversion_info(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::fee::native_conversion_info")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__fee__native_conversion_info(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::fee::pay_fee")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__fee__pay_fee(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: i32,
) -> f32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::fees::collect_sponsored_fees")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__fees__collect_sponsored_fees(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
) -> f32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::fees::create_network_note_sponsorships")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__fees__create_network_note_sponsorships(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
) -> f32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::fees::fee_manager::estimate_note_fee_internal")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__fees__fee_manager__estimate_note_fee_internal(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _arg8: f32,
    _arg9: f32,
    _arg10: f32,
    _arg11: f32,
    _arg12: i32,
    _arg13: i32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::fees::fee_manager::read_fee_asset_id")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__fees__fee_manager__read_fee_asset_id(_ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::interop::eth::build_felt")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__interop__eth__build_felt(_arg0: i32, _arg1: i32) -> f32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::interop::eth::bytes32_to_account_id")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__interop__eth__bytes32_to_account_id(
    _arg0: i32,
    _arg1: i32,
    _arg2: i32,
    _arg3: i32,
    _arg4: i32,
    _arg5: i32,
    _arg6: i32,
    _arg7: i32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::interop::eth::to_account_id")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__interop__eth__to_account_id(
    _arg0: i32,
    _arg1: i32,
    _arg2: i32,
    _arg3: i32,
    _arg4: i32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::note::get_recipient_preimage")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__note__get_recipient_preimage(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::note::input_note_get_storage")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__note__input_note_get_storage(_arg0: i32, _arg1: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::note::note_tag::create_account_target")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__note__note_tag__create_account_target(_arg0: f32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::note::note_tag::create_custom_account_target")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__note__note_tag__create_custom_account_target(
    _arg0: i32,
    _arg1: f32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::note::output_note_get_recipient_preimage")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__note__output_note_get_recipient_preimage(
    _arg0: i32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::notes::fee_sponsorship::prepare_note")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__notes__fee_sponsorship__prepare_note(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: i32,
    _arg7: i32,
    _arg8: i32,
    _arg9: f32,
    _arg10: f32,
    _arg11: f32,
    _arg12: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::notes::p2id::create_output_note")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__notes__p2id__create_output_note(
    _arg0: f32,
    _arg1: f32,
    _arg2: i32,
    _arg3: i32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::notes::p2id::prepare_note")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__notes__p2id__prepare_note(
    _arg0: f32,
    _arg1: f32,
    _arg2: i32,
    _arg3: i32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::notes::tx_fee::create_output_note")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__notes__tx_fee__create_output_note(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::notes::tx_fee::prepare_note")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__notes__tx_fee__prepare_note(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::utils::mem_load_double_word")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__utils__mem_load_double_word(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::utils::mem_load_double_word_unaligned")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__utils__mem_load_double_word_unaligned(_arg0: i32, _ret: i32) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::utils::mem_store_double_word")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__utils__mem_store_double_word(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _arg8: i32,
    _ret: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::utils::mem_store_double_word_unaligned")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__utils__mem_store_double_word_unaligned(
    _arg0: f32,
    _arg1: f32,
    _arg2: f32,
    _arg3: f32,
    _arg4: f32,
    _arg5: f32,
    _arg6: f32,
    _arg7: f32,
    _arg8: i32,
) {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::utils::merge_u32_limbs")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__utils__merge_u32_limbs(_arg0: i32, _arg1: i32) -> f32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::utils::swap_u32_bytes")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__utils__swap_u32_bytes(_arg0: i32) -> i32 {
    unsafe { core::hint::unreachable_unchecked() }
}

#[unsafe(export_name = "miden::standards::wallets::basic::move_note_assets_to_account")]
#[linkage = "weak"]
#[optimize(none)]
#[inline(never)]
pub extern "C" fn miden__standards__wallets__basic__move_note_assets_to_account() {
    unsafe { core::hint::unreachable_unchecked() }
}
