// Sixteen-state machine (campaign 11 ladder 1 boundary rung, generated by
// scratch/c11gen_sm.py): two input bits consumed per step select one of
// four transitions per state (64 arms), four arm breaks, one early return,
// and a step-budget header exit. Exit tag = top nibble.
#[unsafe(no_mangle)]
pub extern "C" fn entrypoint(input1: u32, input2: u32) -> u32 {
    let mut bits = input1;
    let mut acc = input2;
    let mut state = 0u32;
    let mut steps = 0u32;
    let tag = loop {
        if steps >= 48 {
            break 1u32;
        }
        steps = steps.wrapping_add(1);
        let two = bits & 3;
        bits = bits.rotate_right(2);
        match state {
            0 => {
                acc = acc.wrapping_add(0x101);
                state = match two {
                    0 => 14,
                    1 => 14,
                    2 => 14,
                    _ => 6,
                };
            }
            1 => {
                acc ^= 0x202;
                state = match two {
                    0 => 5,
                    1 => 15,
                    2 => 5,
                    _ => 3,
                };
            }
            2 => {
                acc = acc.rotate_left(3);
                state = match two {
                    0 => 14,
                    1 => 9,
                    2 => 4,
                    _ => 2,
                };
            }
            3 => {
                acc = acc.wrapping_mul(9);
                if acc & 7 == 3 {
                    break 2;
                }
                state = match two {
                    0 => 1,
                    1 => 12,
                    2 => 14,
                    _ => 5,
                };
            }
            4 => {
                acc = acc.wrapping_sub(0x505);
                state = match two {
                    0 => 0,
                    1 => 2,
                    2 => 1,
                    _ => 1,
                };
                continue;
            }
            5 => {
                acc = acc.rotate_right(6);
                state = match two {
                    0 => 6,
                    1 => 7,
                    2 => 0,
                    _ => 14,
                };
            }
            6 => {
                acc ^= bits;
                if acc & 0x30 == 0x10 {
                    break 3;
                }
                state = match two {
                    0 => 10,
                    1 => 14,
                    2 => 6,
                    _ => 7,
                };
            }
            7 => {
                acc = acc.wrapping_add(steps);
                state = match two {
                    0 => 9,
                    1 => 15,
                    2 => 0,
                    _ => 2,
                };
            }
            8 => {
                acc = acc.wrapping_add(0x909);
                state = match two {
                    0 => 14,
                    1 => 8,
                    2 => 13,
                    _ => 2,
                };
            }
            9 => {
                acc ^= 0xa0a;
                if steps > 12 && acc & 1 == 1 {
                    break 4;
                }
                state = match two {
                    0 => 8,
                    1 => 10,
                    2 => 7,
                    _ => 9,
                };
                continue;
            }
            10 => {
                acc = acc.rotate_left(11);
                state = match two {
                    0 => 0,
                    1 => 2,
                    2 => 3,
                    _ => 12,
                };
            }
            11 => {
                acc = acc.wrapping_mul(25);
                state = match two {
                    0 => 3,
                    1 => 9,
                    2 => 12,
                    _ => 2,
                };
            }
            12 => {
                acc = acc.wrapping_sub(0xd0d);
                if acc & 0xf0 == 0x50 {
                    break 5;
                }
                state = match two {
                    0 => 0,
                    1 => 0,
                    2 => 6,
                    _ => 6,
                };
            }
            13 => {
                acc = acc.rotate_right(14);
                state = match two {
                    0 => 1,
                    1 => 15,
                    2 => 12,
                    _ => 12,
                };
            }
            14 => {
                acc ^= bits;
                if steps > 20 && two == 3 {
                    return (6 << 28) | ((acc ^ bits) & 0x0fff_ffff);
                }
                state = match two {
                    0 => 13,
                    1 => 2,
                    2 => 6,
                    _ => 8,
                };
                continue;
            }
            _ => {
                acc = acc.wrapping_add(steps);
                state = match two {
                    0 => 10,
                    1 => 2,
                    2 => 9,
                    _ => 10,
                };
            }
        }
        acc = acc.wrapping_add(state);
    };
    (tag << 28) | ((acc ^ state.wrapping_mul(0x0101_0101) ^ steps) & 0x0fff_ffff)
}
