// Nine nested zero-trip-capable loops (campaign 11, generated by
// scratch/c11gen_nest.py 9): every bound is `% 3` of a distinct input bit
// field (guard + bypass edge at all nine levels), labeled breaks from the
// innermost body to levels 1, 4 and 7, an early return, and per-level
// counter folds on every exit path. Exit tag = top nibble. One level
// deeper than `case_nest8.rs`, which is the largest depth that compiles.
#[unsafe(no_mangle)]
pub extern "C" fn entrypoint(input1: u32, input2: u32) -> u32 {
    let n = [
        (input2 >> 2) % 3,
        (input2 >> 4) % 3,
        (input2 >> 6) % 3,
        (input2 >> 8) % 3,
        (input2 >> 10) % 3,
        (input1 >> 2) % 3,
        (input1 >> 4) % 3,
        (input1 >> 6) % 3,
        (input1 >> 8) % 3,
    ];
    let mut x = input1 ^ input2.rotate_left(13);
    let mut tag = 1u32;
    let mut visits = 0u32;
    let mut i0 = 0u32;
    'l0: while i0 < n[0] {
        let mut i1 = 0u32;
        while i1 < n[1] {
            let mut i2 = 0u32;
            while i2 < n[2] {
                let mut i3 = 0u32;
                'l3: while i3 < n[3] {
                    let mut i4 = 0u32;
                    while i4 < n[4] {
                        let mut i5 = 0u32;
                        while i5 < n[5] {
                            let mut i6 = 0u32;
                            'l6: while i6 < n[6] {
                                let mut i7 = 0u32;
                                while i7 < n[7] {
                                    let mut i8 = 0u32;
                                    while i8 < n[8] {
                                        visits = visits.wrapping_add(1);
                                        x = x
                                            .wrapping_mul(0x0808_8405)
                                            .wrapping_add(i8 ^ (i7 << 2) ^ (i6 << 4));
                                        if x & 0x3ff == 0x111 {
                                            return (5 << 28) | ((x ^ visits) & 0x0fff_ffff);
                                        }
                                        if x & 0x1ff == 0x022 {
                                            tag = 4;
                                            x ^= i8;
                                            break 'l6;
                                        }
                                        if x & 0xff0 == 0x300 {
                                            tag = 3;
                                            x = x.rotate_left(1) ^ i7;
                                            break 'l3;
                                        }
                                        if x & 0x7ff0 == 0x5550 {
                                            tag = 2;
                                            x = x.wrapping_sub(i6);
                                            break 'l0;
                                        }
                                        i8 = i8.wrapping_add(1);
                                    }
                                    x = x.wrapping_add(i8 << 16);
                                    i7 = i7.wrapping_add(1);
                                }
                                x = x.wrapping_add(i7 << 14);
                                i6 = i6.wrapping_add(1);
                            }
                            x = x.wrapping_add(i6 << 12);
                            i5 = i5.wrapping_add(1);
                        }
                        x = x.wrapping_add(i5 << 10);
                        i4 = i4.wrapping_add(1);
                    }
                    x = x.wrapping_add(i4 << 8);
                    i3 = i3.wrapping_add(1);
                }
                x = x.wrapping_add(i3 << 6);
                i2 = i2.wrapping_add(1);
            }
            x = x.wrapping_add(i2 << 4);
            i1 = i1.wrapping_add(1);
        }
        x = x.wrapping_add(i1 << 2);
        i0 = i0.wrapping_add(1);
    }
    (tag << 28) | ((x ^ visits.wrapping_mul(0x9e37_79b9) ^ i0) & 0x0fff_ffff)
}
