// zero_trip_guard x exit_values (campaign 14, generated by scratch/c14gen_be.py, K = 6; seven hits the F2 arity-2 gap, eight the F6 overflow):
// 6 shared rotate counts are first used on `m`, then rotate the u64
// accumulator inside the `match` arms of a five-exit loop nest (outer
// `while i < input2 % 97` is zero-trip-capable: LLVM keeps its guard and a
// bypass edge; the inner loop is bottom-test), and again after the nest, so
// the CSE-merged count bands cross the bypass edge, both loops and every
// exit. Exits: outer header, labeled break with a value from a match arm,
// early return, inner break, post-inner break. Exit tag = top nibble.
#[unsafe(no_mangle)]
pub extern "C" fn entrypoint(input1: u32, input2: u32) -> u32 {
    let m = (input1 | 1) as u64;
    let mut x: u64 = m ^ 0x9e37_79b9_7f4a_7c15;
    x ^= m.rotate_left(1);
    x = x.wrapping_add(m.rotate_left(3));
    x = x.wrapping_sub(m.rotate_left(5));
    x ^= m.rotate_left(7);
    x = x.wrapping_add(m.rotate_left(9));
    x = x.wrapping_sub(m.rotate_left(11));
    let n = input2 % 97;
    let jn = (input1 % 5).wrapping_add(2);
    let mut i = 0u32;
    let mut j = 0u32;
    let r = 'outer: loop {
        if i >= n {
            break (1 << 28) | ((x as u32) & 0x0fff_ffff);
        }
        j = 0;
        while j < jn {
            x = x.wrapping_mul(0x0000_0100_0000_01b3) ^ (i.wrapping_add(j) as u64);
            match (x >> 8) % 5 {
                0 => {
                    x ^= x.rotate_left(1);
                    if x & 0xf0 == 0x30 {
                        break 'outer (2 << 28) | ((x.wrapping_add(j as u64) as u32) & 0x0fff_ffff);
                    }
                }
                1 => {
                    x = x.wrapping_add(x.rotate_left(3));
                    if x & 0xf00 == 0x300 {
                        return (3 << 28) | ((x.wrapping_sub(i as u64) as u32) & 0x0fff_ffff);
                    }
                }
                2 => {
                    x = x.wrapping_sub(x.rotate_left(5));
                    if x & 0xf000 == 0x3000 {
                        break;
                    }
                }
                3 => x ^= x.rotate_left(7),
                _ => {}
            }
            j = j.wrapping_add(1);
        }
        if x & 0x7_0000 == 0x3_0000 {
            break (4 << 28) | ((j.wrapping_mul(0x0101_0101)) & 0x0fff_ffff);
        }
        i = i.wrapping_add(1);
    };
    let mut z = x;
    z ^= x.rotate_left(1);
    z = z.wrapping_add(x.rotate_left(3));
    z ^= x.rotate_left(5);
    z = z.wrapping_add(x.rotate_left(7));
    z ^= x.rotate_left(9);
    z = z.wrapping_add(x.rotate_left(11));
    (r & 0xf000_0000)
        | (((r as u32) ^ (z as u32) ^ ((z >> 32) as u32) ^ i.wrapping_mul(0x9e37_79b9))
            & 0x0fff_ffff)
}
