// Many-block function (campaign 11 ladder 5 boundary rung, generated by
// scratch/c11gen_blocks.py): a 200-arm `match` on `input1 % 200` with a
// distinct body per arm, a eight-level decision tree on input bits with 256
// distinct leaves, and a 128-step chain of bit-guarded `if`s — about 800
// basic blocks with block-argument threading between them.

#[inline(never)]
fn match64(a: u32, b: u32) -> u32 {
    let x = b;
    match a % 200 {
        0 => x.wrapping_add(0x1001),
        1 => x ^ 0x2002,
        2 => x.rotate_left(3),
        3 => x.wrapping_mul(9),
        4 => x.wrapping_sub(0x5005),
        5 => x.rotate_right(6),
        6 => x ^ (x >> 7),
        7 => x | 0x8008,
        8 => x.wrapping_add(0x9009),
        9 => x ^ 0xa00a,
        10 => x.rotate_left(11),
        11 => x.wrapping_mul(25),
        12 => x.wrapping_sub(0xd00d),
        13 => x.rotate_right(14),
        14 => x ^ (x >> 15),
        15 => x | 0x10010,
        16 => x.wrapping_add(0x11011),
        17 => x ^ 0x12012,
        18 => x.rotate_left(19),
        19 => x.wrapping_mul(41),
        20 => x.wrapping_sub(0x15015),
        21 => x.rotate_right(22),
        22 => x ^ (x >> 23),
        23 => x | 0x18018,
        24 => x.wrapping_add(0x19019),
        25 => x ^ 0x1a01a,
        26 => x.rotate_left(27),
        27 => x.wrapping_mul(57),
        28 => x.wrapping_sub(0x1d01d),
        29 => x.rotate_right(30),
        30 => x ^ (x >> 31),
        31 => x | 0x20020,
        32 => x.wrapping_add(0x21021),
        33 => x ^ 0x22022,
        34 => x.rotate_left(4),
        35 => x.wrapping_mul(73),
        36 => x.wrapping_sub(0x25025),
        37 => x.rotate_right(7),
        38 => x ^ (x >> 8),
        39 => x | 0x28028,
        40 => x.wrapping_add(0x29029),
        41 => x ^ 0x2a02a,
        42 => x.rotate_left(12),
        43 => x.wrapping_mul(89),
        44 => x.wrapping_sub(0x2d02d),
        45 => x.rotate_right(15),
        46 => x ^ (x >> 16),
        47 => x | 0x30030,
        48 => x.wrapping_add(0x31031),
        49 => x ^ 0x32032,
        50 => x.rotate_left(20),
        51 => x.wrapping_mul(105),
        52 => x.wrapping_sub(0x35035),
        53 => x.rotate_right(23),
        54 => x ^ (x >> 24),
        55 => x | 0x38038,
        56 => x.wrapping_add(0x39039),
        57 => x ^ 0x3a03a,
        58 => x.rotate_left(28),
        59 => x.wrapping_mul(121),
        60 => x.wrapping_sub(0x3d03d),
        61 => x.rotate_right(31),
        62 => x ^ (x >> 1),
        63 => x | 0x40040,
        64 => x.wrapping_add(0x41041),
        65 => x ^ 0x42042,
        66 => x.rotate_left(5),
        67 => x.wrapping_mul(137),
        68 => x.wrapping_sub(0x45045),
        69 => x.rotate_right(8),
        70 => x ^ (x >> 9),
        71 => x | 0x48048,
        72 => x.wrapping_add(0x49049),
        73 => x ^ 0x4a04a,
        74 => x.rotate_left(13),
        75 => x.wrapping_mul(153),
        76 => x.wrapping_sub(0x4d04d),
        77 => x.rotate_right(16),
        78 => x ^ (x >> 17),
        79 => x | 0x50050,
        80 => x.wrapping_add(0x51051),
        81 => x ^ 0x52052,
        82 => x.rotate_left(21),
        83 => x.wrapping_mul(169),
        84 => x.wrapping_sub(0x55055),
        85 => x.rotate_right(24),
        86 => x ^ (x >> 25),
        87 => x | 0x58058,
        88 => x.wrapping_add(0x59059),
        89 => x ^ 0x5a05a,
        90 => x.rotate_left(29),
        91 => x.wrapping_mul(185),
        92 => x.wrapping_sub(0x5d05d),
        93 => x.rotate_right(1),
        94 => x ^ (x >> 2),
        95 => x | 0x60060,
        96 => x.wrapping_add(0x61061),
        97 => x ^ 0x62062,
        98 => x.rotate_left(6),
        99 => x.wrapping_mul(201),
        100 => x.wrapping_sub(0x65065),
        101 => x.rotate_right(9),
        102 => x ^ (x >> 10),
        103 => x | 0x68068,
        104 => x.wrapping_add(0x69069),
        105 => x ^ 0x6a06a,
        106 => x.rotate_left(14),
        107 => x.wrapping_mul(217),
        108 => x.wrapping_sub(0x6d06d),
        109 => x.rotate_right(17),
        110 => x ^ (x >> 18),
        111 => x | 0x70070,
        112 => x.wrapping_add(0x71071),
        113 => x ^ 0x72072,
        114 => x.rotate_left(22),
        115 => x.wrapping_mul(233),
        116 => x.wrapping_sub(0x75075),
        117 => x.rotate_right(25),
        118 => x ^ (x >> 26),
        119 => x | 0x78078,
        120 => x.wrapping_add(0x79079),
        121 => x ^ 0x7a07a,
        122 => x.rotate_left(30),
        123 => x.wrapping_mul(249),
        124 => x.wrapping_sub(0x7d07d),
        125 => x.rotate_right(2),
        126 => x ^ (x >> 3),
        127 => x | 0x80080,
        128 => x.wrapping_add(0x81081),
        129 => x ^ 0x82082,
        130 => x.rotate_left(7),
        131 => x.wrapping_mul(265),
        132 => x.wrapping_sub(0x85085),
        133 => x.rotate_right(10),
        134 => x ^ (x >> 11),
        135 => x | 0x88088,
        136 => x.wrapping_add(0x89089),
        137 => x ^ 0x8a08a,
        138 => x.rotate_left(15),
        139 => x.wrapping_mul(281),
        140 => x.wrapping_sub(0x8d08d),
        141 => x.rotate_right(18),
        142 => x ^ (x >> 19),
        143 => x | 0x90090,
        144 => x.wrapping_add(0x91091),
        145 => x ^ 0x92092,
        146 => x.rotate_left(23),
        147 => x.wrapping_mul(297),
        148 => x.wrapping_sub(0x95095),
        149 => x.rotate_right(26),
        150 => x ^ (x >> 27),
        151 => x | 0x98098,
        152 => x.wrapping_add(0x99099),
        153 => x ^ 0x9a09a,
        154 => x.rotate_left(31),
        155 => x.wrapping_mul(313),
        156 => x.wrapping_sub(0x9d09d),
        157 => x.rotate_right(3),
        158 => x ^ (x >> 4),
        159 => x | 0xa00a0,
        160 => x.wrapping_add(0xa10a1),
        161 => x ^ 0xa20a2,
        162 => x.rotate_left(8),
        163 => x.wrapping_mul(329),
        164 => x.wrapping_sub(0xa50a5),
        165 => x.rotate_right(11),
        166 => x ^ (x >> 12),
        167 => x | 0xa80a8,
        168 => x.wrapping_add(0xa90a9),
        169 => x ^ 0xaa0aa,
        170 => x.rotate_left(16),
        171 => x.wrapping_mul(345),
        172 => x.wrapping_sub(0xad0ad),
        173 => x.rotate_right(19),
        174 => x ^ (x >> 20),
        175 => x | 0xb00b0,
        176 => x.wrapping_add(0xb10b1),
        177 => x ^ 0xb20b2,
        178 => x.rotate_left(24),
        179 => x.wrapping_mul(361),
        180 => x.wrapping_sub(0xb50b5),
        181 => x.rotate_right(27),
        182 => x ^ (x >> 28),
        183 => x | 0xb80b8,
        184 => x.wrapping_add(0xb90b9),
        185 => x ^ 0xba0ba,
        186 => x.rotate_left(1),
        187 => x.wrapping_mul(377),
        188 => x.wrapping_sub(0xbd0bd),
        189 => x.rotate_right(4),
        190 => x ^ (x >> 5),
        191 => x | 0xc00c0,
        192 => x.wrapping_add(0xc10c1),
        193 => x ^ 0xc20c2,
        194 => x.rotate_left(9),
        195 => x.wrapping_mul(393),
        196 => x.wrapping_sub(0xc50c5),
        197 => x.rotate_right(12),
        198 => x ^ (x >> 13),
        _ => x | 0xc80c8,
    }
}

#[inline(never)]
fn tree6(a: u32, b: u32) -> u32 {
    let x = b;
    if (a >> 1) & 1 == 0 {
        if (a >> 6) & 1 == 0 {
            if (a >> 11) & 1 == 0 {
                if (a >> 16) & 1 == 0 {
                    if (a >> 21) & 1 == 0 {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x8008
                                } else {
                                    x.wrapping_add(0x9009)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0xa00a
                                } else {
                                    x.rotate_left(11)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(25)
                                } else {
                                    x.wrapping_sub(0xd00d)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(14)
                                } else {
                                    x ^ (x >> 15)
                                }
                            }
                        }
                    } else {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x10010
                                } else {
                                    x.wrapping_add(0x11011)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x12012
                                } else {
                                    x.rotate_left(19)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(41)
                                } else {
                                    x.wrapping_sub(0x15015)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(22)
                                } else {
                                    x ^ (x >> 23)
                                }
                            }
                        }
                    }
                } else {
                    if (a >> 21) & 1 == 0 {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x18018
                                } else {
                                    x.wrapping_add(0x19019)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x1a01a
                                } else {
                                    x.rotate_left(27)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(57)
                                } else {
                                    x.wrapping_sub(0x1d01d)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(30)
                                } else {
                                    x ^ (x >> 31)
                                }
                            }
                        }
                    } else {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x20020
                                } else {
                                    x.wrapping_add(0x21021)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x22022
                                } else {
                                    x.rotate_left(4)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(73)
                                } else {
                                    x.wrapping_sub(0x25025)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(7)
                                } else {
                                    x ^ (x >> 8)
                                }
                            }
                        }
                    }
                }
            } else {
                if (a >> 16) & 1 == 0 {
                    if (a >> 21) & 1 == 0 {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x28028
                                } else {
                                    x.wrapping_add(0x29029)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x2a02a
                                } else {
                                    x.rotate_left(12)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(89)
                                } else {
                                    x.wrapping_sub(0x2d02d)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(15)
                                } else {
                                    x ^ (x >> 16)
                                }
                            }
                        }
                    } else {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x30030
                                } else {
                                    x.wrapping_add(0x31031)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x32032
                                } else {
                                    x.rotate_left(20)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(105)
                                } else {
                                    x.wrapping_sub(0x35035)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(23)
                                } else {
                                    x ^ (x >> 24)
                                }
                            }
                        }
                    }
                } else {
                    if (a >> 21) & 1 == 0 {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x38038
                                } else {
                                    x.wrapping_add(0x39039)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x3a03a
                                } else {
                                    x.rotate_left(28)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(121)
                                } else {
                                    x.wrapping_sub(0x3d03d)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(31)
                                } else {
                                    x ^ (x >> 1)
                                }
                            }
                        }
                    } else {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x40040
                                } else {
                                    x.wrapping_add(0x41041)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x42042
                                } else {
                                    x.rotate_left(5)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(137)
                                } else {
                                    x.wrapping_sub(0x45045)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(8)
                                } else {
                                    x ^ (x >> 9)
                                }
                            }
                        }
                    }
                }
            }
        } else {
            if (a >> 11) & 1 == 0 {
                if (a >> 16) & 1 == 0 {
                    if (a >> 21) & 1 == 0 {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x48048
                                } else {
                                    x.wrapping_add(0x49049)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x4a04a
                                } else {
                                    x.rotate_left(13)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(153)
                                } else {
                                    x.wrapping_sub(0x4d04d)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(16)
                                } else {
                                    x ^ (x >> 17)
                                }
                            }
                        }
                    } else {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x50050
                                } else {
                                    x.wrapping_add(0x51051)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x52052
                                } else {
                                    x.rotate_left(21)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(169)
                                } else {
                                    x.wrapping_sub(0x55055)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(24)
                                } else {
                                    x ^ (x >> 25)
                                }
                            }
                        }
                    }
                } else {
                    if (a >> 21) & 1 == 0 {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x58058
                                } else {
                                    x.wrapping_add(0x59059)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x5a05a
                                } else {
                                    x.rotate_left(29)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(185)
                                } else {
                                    x.wrapping_sub(0x5d05d)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(1)
                                } else {
                                    x ^ (x >> 2)
                                }
                            }
                        }
                    } else {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x60060
                                } else {
                                    x.wrapping_add(0x61061)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x62062
                                } else {
                                    x.rotate_left(6)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(201)
                                } else {
                                    x.wrapping_sub(0x65065)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(9)
                                } else {
                                    x ^ (x >> 10)
                                }
                            }
                        }
                    }
                }
            } else {
                if (a >> 16) & 1 == 0 {
                    if (a >> 21) & 1 == 0 {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x68068
                                } else {
                                    x.wrapping_add(0x69069)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x6a06a
                                } else {
                                    x.rotate_left(14)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(217)
                                } else {
                                    x.wrapping_sub(0x6d06d)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(17)
                                } else {
                                    x ^ (x >> 18)
                                }
                            }
                        }
                    } else {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x70070
                                } else {
                                    x.wrapping_add(0x71071)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x72072
                                } else {
                                    x.rotate_left(22)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(233)
                                } else {
                                    x.wrapping_sub(0x75075)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(25)
                                } else {
                                    x ^ (x >> 26)
                                }
                            }
                        }
                    }
                } else {
                    if (a >> 21) & 1 == 0 {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x78078
                                } else {
                                    x.wrapping_add(0x79079)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x7a07a
                                } else {
                                    x.rotate_left(30)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(249)
                                } else {
                                    x.wrapping_sub(0x7d07d)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(2)
                                } else {
                                    x ^ (x >> 3)
                                }
                            }
                        }
                    } else {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x80080
                                } else {
                                    x.wrapping_add(0x81081)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x82082
                                } else {
                                    x.rotate_left(7)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(265)
                                } else {
                                    x.wrapping_sub(0x85085)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(10)
                                } else {
                                    x ^ (x >> 11)
                                }
                            }
                        }
                    }
                }
            }
        }
    } else {
        if (a >> 6) & 1 == 0 {
            if (a >> 11) & 1 == 0 {
                if (a >> 16) & 1 == 0 {
                    if (a >> 21) & 1 == 0 {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x88088
                                } else {
                                    x.wrapping_add(0x89089)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x8a08a
                                } else {
                                    x.rotate_left(15)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(281)
                                } else {
                                    x.wrapping_sub(0x8d08d)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(18)
                                } else {
                                    x ^ (x >> 19)
                                }
                            }
                        }
                    } else {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x90090
                                } else {
                                    x.wrapping_add(0x91091)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x92092
                                } else {
                                    x.rotate_left(23)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(297)
                                } else {
                                    x.wrapping_sub(0x95095)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(26)
                                } else {
                                    x ^ (x >> 27)
                                }
                            }
                        }
                    }
                } else {
                    if (a >> 21) & 1 == 0 {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x98098
                                } else {
                                    x.wrapping_add(0x99099)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x9a09a
                                } else {
                                    x.rotate_left(31)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(313)
                                } else {
                                    x.wrapping_sub(0x9d09d)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(3)
                                } else {
                                    x ^ (x >> 4)
                                }
                            }
                        }
                    } else {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0xa00a0
                                } else {
                                    x.wrapping_add(0xa10a1)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0xa20a2
                                } else {
                                    x.rotate_left(8)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(329)
                                } else {
                                    x.wrapping_sub(0xa50a5)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(11)
                                } else {
                                    x ^ (x >> 12)
                                }
                            }
                        }
                    }
                }
            } else {
                if (a >> 16) & 1 == 0 {
                    if (a >> 21) & 1 == 0 {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0xa80a8
                                } else {
                                    x.wrapping_add(0xa90a9)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0xaa0aa
                                } else {
                                    x.rotate_left(16)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(345)
                                } else {
                                    x.wrapping_sub(0xad0ad)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(19)
                                } else {
                                    x ^ (x >> 20)
                                }
                            }
                        }
                    } else {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0xb00b0
                                } else {
                                    x.wrapping_add(0xb10b1)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0xb20b2
                                } else {
                                    x.rotate_left(24)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(361)
                                } else {
                                    x.wrapping_sub(0xb50b5)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(27)
                                } else {
                                    x ^ (x >> 28)
                                }
                            }
                        }
                    }
                } else {
                    if (a >> 21) & 1 == 0 {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0xb80b8
                                } else {
                                    x.wrapping_add(0xb90b9)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0xba0ba
                                } else {
                                    x.rotate_left(1)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(377)
                                } else {
                                    x.wrapping_sub(0xbd0bd)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(4)
                                } else {
                                    x ^ (x >> 5)
                                }
                            }
                        }
                    } else {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0xc00c0
                                } else {
                                    x.wrapping_add(0xc10c1)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0xc20c2
                                } else {
                                    x.rotate_left(9)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(393)
                                } else {
                                    x.wrapping_sub(0xc50c5)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(12)
                                } else {
                                    x ^ (x >> 13)
                                }
                            }
                        }
                    }
                }
            }
        } else {
            if (a >> 11) & 1 == 0 {
                if (a >> 16) & 1 == 0 {
                    if (a >> 21) & 1 == 0 {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0xc80c8
                                } else {
                                    x.wrapping_add(0xc90c9)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0xca0ca
                                } else {
                                    x.rotate_left(17)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(409)
                                } else {
                                    x.wrapping_sub(0xcd0cd)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(20)
                                } else {
                                    x ^ (x >> 21)
                                }
                            }
                        }
                    } else {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0xd00d0
                                } else {
                                    x.wrapping_add(0xd10d1)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0xd20d2
                                } else {
                                    x.rotate_left(25)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(425)
                                } else {
                                    x.wrapping_sub(0xd50d5)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(28)
                                } else {
                                    x ^ (x >> 29)
                                }
                            }
                        }
                    }
                } else {
                    if (a >> 21) & 1 == 0 {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0xd80d8
                                } else {
                                    x.wrapping_add(0xd90d9)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0xda0da
                                } else {
                                    x.rotate_left(2)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(441)
                                } else {
                                    x.wrapping_sub(0xdd0dd)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(5)
                                } else {
                                    x ^ (x >> 6)
                                }
                            }
                        }
                    } else {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0xe00e0
                                } else {
                                    x.wrapping_add(0xe10e1)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0xe20e2
                                } else {
                                    x.rotate_left(10)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(457)
                                } else {
                                    x.wrapping_sub(0xe50e5)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(13)
                                } else {
                                    x ^ (x >> 14)
                                }
                            }
                        }
                    }
                }
            } else {
                if (a >> 16) & 1 == 0 {
                    if (a >> 21) & 1 == 0 {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0xe80e8
                                } else {
                                    x.wrapping_add(0xe90e9)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0xea0ea
                                } else {
                                    x.rotate_left(18)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(473)
                                } else {
                                    x.wrapping_sub(0xed0ed)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(21)
                                } else {
                                    x ^ (x >> 22)
                                }
                            }
                        }
                    } else {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0xf00f0
                                } else {
                                    x.wrapping_add(0xf10f1)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0xf20f2
                                } else {
                                    x.rotate_left(26)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(489)
                                } else {
                                    x.wrapping_sub(0xf50f5)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(29)
                                } else {
                                    x ^ (x >> 30)
                                }
                            }
                        }
                    }
                } else {
                    if (a >> 21) & 1 == 0 {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0xf80f8
                                } else {
                                    x.wrapping_add(0xf90f9)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0xfa0fa
                                } else {
                                    x.rotate_left(3)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(505)
                                } else {
                                    x.wrapping_sub(0xfd0fd)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(6)
                                } else {
                                    x ^ (x >> 7)
                                }
                            }
                        }
                    } else {
                        if (a >> 26) & 1 == 0 {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x | 0x100100
                                } else {
                                    x.wrapping_add(0x101101)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x ^ 0x102102
                                } else {
                                    x.rotate_left(11)
                                }
                            }
                        } else {
                            if (a >> 31) & 1 == 0 {
                                if (a >> 4) & 1 == 0 {
                                    x.wrapping_mul(521)
                                } else {
                                    x.wrapping_sub(0x105105)
                                }
                            } else {
                                if (a >> 4) & 1 == 0 {
                                    x.rotate_right(14)
                                } else {
                                    x ^ (x >> 15)
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

#[inline(never)]
fn chain48(a: u32, b: u32) -> u32 {
    let mut x = b;
    if (a >> 0) & 1 == 1 {
        x = x.wrapping_mul(9);
    }
    if (a >> 7) & 1 == 1 {
        x = x.wrapping_sub(0x5005);
    }
    if (a >> 14) & 1 == 1 {
        x = x.rotate_right(6);
    }
    if (a >> 21) & 1 == 1 {
        x = x ^ (x >> 7);
    }
    if (a >> 28) & 1 == 1 {
        x = x | 0x8008;
    }
    if (a >> 3) & 1 == 1 {
        x = x.wrapping_add(0x9009);
    }
    if (a >> 10) & 1 == 1 {
        x = x ^ 0xa00a;
    }
    if (a >> 17) & 1 == 1 {
        x = x.rotate_left(11);
    }
    if (a >> 24) & 1 == 1 {
        x = x.wrapping_mul(25);
    }
    if (a >> 31) & 1 == 1 {
        x = x.wrapping_sub(0xd00d);
    }
    if (a >> 6) & 1 == 1 {
        x = x.rotate_right(14);
    }
    if (a >> 13) & 1 == 1 {
        x = x ^ (x >> 15);
    }
    if (a >> 20) & 1 == 1 {
        x = x | 0x10010;
    }
    if (a >> 27) & 1 == 1 {
        x = x.wrapping_add(0x11011);
    }
    if (a >> 2) & 1 == 1 {
        x = x ^ 0x12012;
    }
    if (a >> 9) & 1 == 1 {
        x = x.rotate_left(19);
    }
    if (a >> 16) & 1 == 1 {
        x = x.wrapping_mul(41);
    }
    if (a >> 23) & 1 == 1 {
        x = x.wrapping_sub(0x15015);
    }
    if (a >> 30) & 1 == 1 {
        x = x.rotate_right(22);
    }
    if (a >> 5) & 1 == 1 {
        x = x ^ (x >> 23);
    }
    if (a >> 12) & 1 == 1 {
        x = x | 0x18018;
    }
    if (a >> 19) & 1 == 1 {
        x = x.wrapping_add(0x19019);
    }
    if (a >> 26) & 1 == 1 {
        x = x ^ 0x1a01a;
    }
    if (a >> 1) & 1 == 1 {
        x = x.rotate_left(27);
    }
    if (a >> 8) & 1 == 1 {
        x = x.wrapping_mul(57);
    }
    if (a >> 15) & 1 == 1 {
        x = x.wrapping_sub(0x1d01d);
    }
    if (a >> 22) & 1 == 1 {
        x = x.rotate_right(30);
    }
    if (a >> 29) & 1 == 1 {
        x = x ^ (x >> 31);
    }
    if (a >> 4) & 1 == 1 {
        x = x | 0x20020;
    }
    if (a >> 11) & 1 == 1 {
        x = x.wrapping_add(0x21021);
    }
    if (a >> 18) & 1 == 1 {
        x = x ^ 0x22022;
    }
    if (a >> 25) & 1 == 1 {
        x = x.rotate_left(4);
    }
    if (a >> 0) & 1 == 1 {
        x = x.wrapping_mul(73);
    }
    if (a >> 7) & 1 == 1 {
        x = x.wrapping_sub(0x25025);
    }
    if (a >> 14) & 1 == 1 {
        x = x.rotate_right(7);
    }
    if (a >> 21) & 1 == 1 {
        x = x ^ (x >> 8);
    }
    if (a >> 28) & 1 == 1 {
        x = x | 0x28028;
    }
    if (a >> 3) & 1 == 1 {
        x = x.wrapping_add(0x29029);
    }
    if (a >> 10) & 1 == 1 {
        x = x ^ 0x2a02a;
    }
    if (a >> 17) & 1 == 1 {
        x = x.rotate_left(12);
    }
    if (a >> 24) & 1 == 1 {
        x = x.wrapping_mul(89);
    }
    if (a >> 31) & 1 == 1 {
        x = x.wrapping_sub(0x2d02d);
    }
    if (a >> 6) & 1 == 1 {
        x = x.rotate_right(15);
    }
    if (a >> 13) & 1 == 1 {
        x = x ^ (x >> 16);
    }
    if (a >> 20) & 1 == 1 {
        x = x | 0x30030;
    }
    if (a >> 27) & 1 == 1 {
        x = x.wrapping_add(0x31031);
    }
    if (a >> 2) & 1 == 1 {
        x = x ^ 0x32032;
    }
    if (a >> 9) & 1 == 1 {
        x = x.rotate_left(20);
    }
    if (a >> 16) & 1 == 1 {
        x = x.wrapping_mul(105);
    }
    if (a >> 23) & 1 == 1 {
        x = x.wrapping_sub(0x35035);
    }
    if (a >> 30) & 1 == 1 {
        x = x.rotate_right(23);
    }
    if (a >> 5) & 1 == 1 {
        x = x ^ (x >> 24);
    }
    if (a >> 12) & 1 == 1 {
        x = x | 0x38038;
    }
    if (a >> 19) & 1 == 1 {
        x = x.wrapping_add(0x39039);
    }
    if (a >> 26) & 1 == 1 {
        x = x ^ 0x3a03a;
    }
    if (a >> 1) & 1 == 1 {
        x = x.rotate_left(28);
    }
    if (a >> 8) & 1 == 1 {
        x = x.wrapping_mul(121);
    }
    if (a >> 15) & 1 == 1 {
        x = x.wrapping_sub(0x3d03d);
    }
    if (a >> 22) & 1 == 1 {
        x = x.rotate_right(31);
    }
    if (a >> 29) & 1 == 1 {
        x = x ^ (x >> 1);
    }
    if (a >> 4) & 1 == 1 {
        x = x | 0x40040;
    }
    if (a >> 11) & 1 == 1 {
        x = x.wrapping_add(0x41041);
    }
    if (a >> 18) & 1 == 1 {
        x = x ^ 0x42042;
    }
    if (a >> 25) & 1 == 1 {
        x = x.rotate_left(5);
    }
    if (a >> 0) & 1 == 1 {
        x = x.wrapping_mul(137);
    }
    if (a >> 7) & 1 == 1 {
        x = x.wrapping_sub(0x45045);
    }
    if (a >> 14) & 1 == 1 {
        x = x.rotate_right(8);
    }
    if (a >> 21) & 1 == 1 {
        x = x ^ (x >> 9);
    }
    if (a >> 28) & 1 == 1 {
        x = x | 0x48048;
    }
    if (a >> 3) & 1 == 1 {
        x = x.wrapping_add(0x49049);
    }
    if (a >> 10) & 1 == 1 {
        x = x ^ 0x4a04a;
    }
    if (a >> 17) & 1 == 1 {
        x = x.rotate_left(13);
    }
    if (a >> 24) & 1 == 1 {
        x = x.wrapping_mul(153);
    }
    if (a >> 31) & 1 == 1 {
        x = x.wrapping_sub(0x4d04d);
    }
    if (a >> 6) & 1 == 1 {
        x = x.rotate_right(16);
    }
    if (a >> 13) & 1 == 1 {
        x = x ^ (x >> 17);
    }
    if (a >> 20) & 1 == 1 {
        x = x | 0x50050;
    }
    if (a >> 27) & 1 == 1 {
        x = x.wrapping_add(0x51051);
    }
    if (a >> 2) & 1 == 1 {
        x = x ^ 0x52052;
    }
    if (a >> 9) & 1 == 1 {
        x = x.rotate_left(21);
    }
    if (a >> 16) & 1 == 1 {
        x = x.wrapping_mul(169);
    }
    if (a >> 23) & 1 == 1 {
        x = x.wrapping_sub(0x55055);
    }
    if (a >> 30) & 1 == 1 {
        x = x.rotate_right(24);
    }
    if (a >> 5) & 1 == 1 {
        x = x ^ (x >> 25);
    }
    if (a >> 12) & 1 == 1 {
        x = x | 0x58058;
    }
    if (a >> 19) & 1 == 1 {
        x = x.wrapping_add(0x59059);
    }
    if (a >> 26) & 1 == 1 {
        x = x ^ 0x5a05a;
    }
    if (a >> 1) & 1 == 1 {
        x = x.rotate_left(29);
    }
    if (a >> 8) & 1 == 1 {
        x = x.wrapping_mul(185);
    }
    if (a >> 15) & 1 == 1 {
        x = x.wrapping_sub(0x5d05d);
    }
    if (a >> 22) & 1 == 1 {
        x = x.rotate_right(1);
    }
    if (a >> 29) & 1 == 1 {
        x = x ^ (x >> 2);
    }
    if (a >> 4) & 1 == 1 {
        x = x | 0x60060;
    }
    if (a >> 11) & 1 == 1 {
        x = x.wrapping_add(0x61061);
    }
    if (a >> 18) & 1 == 1 {
        x = x ^ 0x62062;
    }
    if (a >> 25) & 1 == 1 {
        x = x.rotate_left(6);
    }
    if (a >> 0) & 1 == 1 {
        x = x.wrapping_mul(201);
    }
    if (a >> 7) & 1 == 1 {
        x = x.wrapping_sub(0x65065);
    }
    if (a >> 14) & 1 == 1 {
        x = x.rotate_right(9);
    }
    if (a >> 21) & 1 == 1 {
        x = x ^ (x >> 10);
    }
    if (a >> 28) & 1 == 1 {
        x = x | 0x68068;
    }
    if (a >> 3) & 1 == 1 {
        x = x.wrapping_add(0x69069);
    }
    if (a >> 10) & 1 == 1 {
        x = x ^ 0x6a06a;
    }
    if (a >> 17) & 1 == 1 {
        x = x.rotate_left(14);
    }
    if (a >> 24) & 1 == 1 {
        x = x.wrapping_mul(217);
    }
    if (a >> 31) & 1 == 1 {
        x = x.wrapping_sub(0x6d06d);
    }
    if (a >> 6) & 1 == 1 {
        x = x.rotate_right(17);
    }
    if (a >> 13) & 1 == 1 {
        x = x ^ (x >> 18);
    }
    if (a >> 20) & 1 == 1 {
        x = x | 0x70070;
    }
    if (a >> 27) & 1 == 1 {
        x = x.wrapping_add(0x71071);
    }
    if (a >> 2) & 1 == 1 {
        x = x ^ 0x72072;
    }
    if (a >> 9) & 1 == 1 {
        x = x.rotate_left(22);
    }
    if (a >> 16) & 1 == 1 {
        x = x.wrapping_mul(233);
    }
    if (a >> 23) & 1 == 1 {
        x = x.wrapping_sub(0x75075);
    }
    if (a >> 30) & 1 == 1 {
        x = x.rotate_right(25);
    }
    if (a >> 5) & 1 == 1 {
        x = x ^ (x >> 26);
    }
    if (a >> 12) & 1 == 1 {
        x = x | 0x78078;
    }
    if (a >> 19) & 1 == 1 {
        x = x.wrapping_add(0x79079);
    }
    if (a >> 26) & 1 == 1 {
        x = x ^ 0x7a07a;
    }
    if (a >> 1) & 1 == 1 {
        x = x.rotate_left(30);
    }
    if (a >> 8) & 1 == 1 {
        x = x.wrapping_mul(249);
    }
    if (a >> 15) & 1 == 1 {
        x = x.wrapping_sub(0x7d07d);
    }
    if (a >> 22) & 1 == 1 {
        x = x.rotate_right(2);
    }
    if (a >> 29) & 1 == 1 {
        x = x ^ (x >> 3);
    }
    if (a >> 4) & 1 == 1 {
        x = x | 0x80080;
    }
    if (a >> 11) & 1 == 1 {
        x = x.wrapping_add(0x81081);
    }
    if (a >> 18) & 1 == 1 {
        x = x ^ 0x82082;
    }
    if (a >> 25) & 1 == 1 {
        x = x.rotate_left(7);
    }
    x
}

#[unsafe(no_mangle)]
pub extern "C" fn entrypoint(input1: u32, input2: u32) -> u32 {
    match64(input1, input2)
        ^ tree6(input2, input1).rotate_left(9)
        ^ chain48(input1 ^ input2, input2).rotate_left(18)
}
