// chain_window x sm16 (campaign 14, generated by scratch/c14gen_sm.py, K = 6; eight hits the F2 arity-2 gap):
// 6 shared rotate counts are first used on `y` before a sixteen-state
// machine (two input bits per step, four-way transitions, four arm breaks,
// one early return, a step-budget exit), then rotate the machine's u64
// accumulator inside the arms, then rotate the final accumulator after the
// machine. The CSE-merged count bands are live across the whole machine
// (its jump-threaded nested loops and every dispatch arm). Exit tag = top
// nibble.
#[unsafe(no_mangle)]
pub extern "C" fn entrypoint(input1: u32, input2: u32) -> u32 {
    let y = ((input2 ^ 0x9e37_79b9) as u64) | 2;
    let mut acc: u64 = y | 1;
    acc ^= y.rotate_left(1);
    acc = acc.wrapping_add(y.rotate_left(3));
    acc = acc.wrapping_sub(y.rotate_left(5));
    acc ^= y.rotate_left(7);
    acc = acc.wrapping_add(y.rotate_left(9));
    acc = acc.wrapping_sub(y.rotate_left(11));
    let mut bits = input1;
    let mut state = 0u32;
    let mut steps = 0u32;
    let tag = loop {
        if steps >= 40 {
            break 1u32;
        }
        steps = steps.wrapping_add(1);
        let two = bits & 3;
        bits = bits.rotate_right(2);
        match state {
            0 => {
                acc ^= acc.rotate_left(1);
                state = match two {
                    0 => 3,
                    1 => 7,
                    2 => 8,
                    _ => 8,
                };
            }
            1 => {
                acc = acc.wrapping_add(acc.rotate_left(3));
                state = match two {
                    0 => 9,
                    1 => 2,
                    2 => 14,
                    _ => 9,
                };
            }
            2 => {
                acc = acc.wrapping_sub(acc.rotate_left(5));
                state = match two {
                    0 => 14,
                    1 => 12,
                    2 => 12,
                    _ => 3,
                };
            }
            3 => {
                acc ^= bits as u64 ^ acc.rotate_left(7);
                if acc & 7 == 3 {
                    break 2;
                }
                state = match two {
                    0 => 8,
                    1 => 7,
                    2 => 10,
                    _ => 11,
                };
            }
            4 => {
                acc ^= acc.rotate_left(9);
                state = match two {
                    0 => 8,
                    1 => 11,
                    2 => 4,
                    _ => 5,
                };
                continue;
            }
            5 => {
                acc = acc.wrapping_add(acc.rotate_left(11));
                state = match two {
                    0 => 8,
                    1 => 5,
                    2 => 0,
                    _ => 2,
                };
            }
            6 => {
                acc = acc.wrapping_sub(acc.rotate_left(1));
                if acc & 0x30 == 0x10 {
                    break 3;
                }
                state = match two {
                    0 => 3,
                    1 => 10,
                    2 => 0,
                    _ => 2,
                };
            }
            7 => {
                acc ^= bits as u64 ^ acc.rotate_left(3);
                state = match two {
                    0 => 8,
                    1 => 6,
                    2 => 12,
                    _ => 12,
                };
            }
            8 => {
                acc ^= acc.rotate_left(5);
                state = match two {
                    0 => 14,
                    1 => 3,
                    2 => 3,
                    _ => 11,
                };
            }
            9 => {
                acc = acc.wrapping_add(acc.rotate_left(7));
                if steps > 12 && acc & 1 == 1 {
                    break 4;
                }
                state = match two {
                    0 => 5,
                    1 => 3,
                    2 => 15,
                    _ => 6,
                };
                continue;
            }
            10 => {
                acc = acc.wrapping_sub(acc.rotate_left(9));
                state = match two {
                    0 => 8,
                    1 => 14,
                    2 => 6,
                    _ => 15,
                };
            }
            11 => {
                acc ^= bits as u64 ^ acc.rotate_left(11);
                state = match two {
                    0 => 9,
                    1 => 8,
                    2 => 3,
                    _ => 3,
                };
            }
            12 => {
                acc ^= acc.rotate_left(1);
                if acc & 0xf0 == 0x50 {
                    break 5;
                }
                state = match two {
                    0 => 2,
                    1 => 8,
                    2 => 8,
                    _ => 3,
                };
            }
            13 => {
                acc = acc.wrapping_add(acc.rotate_left(3));
                state = match two {
                    0 => 0,
                    1 => 5,
                    2 => 13,
                    _ => 3,
                };
            }
            14 => {
                acc = acc.wrapping_sub(acc.rotate_left(5));
                if steps > 20 && two == 3 {
                    return (6 << 28) | (((acc as u32) ^ bits) & 0x0fff_ffff);
                }
                state = match two {
                    0 => 2,
                    1 => 13,
                    2 => 15,
                    _ => 5,
                };
                continue;
            }
            _ => {
                acc ^= bits as u64 ^ acc.rotate_left(7);
                state = match two {
                    0 => 12,
                    1 => 14,
                    2 => 9,
                    _ => 15,
                };
            }
        }
        acc = acc.wrapping_add(state as u64);
    };
    let mut r = acc;
    r ^= acc.rotate_left(1);
    r = r.wrapping_add(acc.rotate_left(3));
    r ^= acc.rotate_left(5);
    r = r.wrapping_add(acc.rotate_left(7));
    r ^= acc.rotate_left(9);
    r = r.wrapping_add(acc.rotate_left(11));
    (tag << 28)
        | (((r as u32) ^ ((r >> 32) as u32) ^ state.wrapping_mul(0x0101_0101) ^ steps)
            & 0x0fff_ffff)
}
